-- Create cities_data table for dynamic city pages
CREATE TABLE IF NOT EXISTS cities_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  city_name TEXT NOT NULL,
  state TEXT,
  content TEXT,
  article_content TEXT,
  meta_title TEXT,
  meta_description TEXT,
  population INTEGER,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on slug for faster lookups
CREATE INDEX IF NOT EXISTS idx_cities_data_slug ON cities_data(slug);

-- Create index on is_active for filtering active cities
CREATE INDEX IF NOT EXISTS idx_cities_data_active ON cities_data(is_active);

-- Enable Row Level Security (RLS)
ALTER TABLE cities_data ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists to avoid conflicts
DROP POLICY IF EXISTS "Allow public read access" ON cities_data;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON cities_data
  FOR SELECT USING (true);

-- Insert sample data
INSERT INTO cities_data (slug, city_name, state, content, meta_title, meta_description, is_active) VALUES
  ('adjuntas-107', 'Adjuntas', 'PR', 'Plumbing issues in Adjuntas can happen at any time. When you face an urgent plumbing emergency, finding a reliable expert fast is key to preventing major water damage to your property. Our network connects you with verified local experts who provide rapid-response services.', '24/7 Emergency Plumbing in Adjuntas | Apex Plumbing', 'Expert emergency plumbing services in Adjuntas. 24/7 availability for burst pipes, sewer line backups, and all plumbing emergencies. Call now for rapid response.', true),
  ('san-juan-101', 'San Juan', 'PR', 'San Juan residents trust our emergency plumbing services. From burst pipes to sewer line backups, our verified local experts provide rapid-response services to resolve your plumbing crisis safely and professionally.', '24/7 Emergency Plumbing in San Juan | Apex Plumbing', 'Expert emergency plumbing services in San Juan. 24/7 availability for burst pipes, sewer line backups, and all plumbing emergencies. Call now for rapid response.', true),
  ('ponce-102', 'Ponce', 'PR', 'Ponce plumbing emergencies require immediate attention. Our network of verified local plumbers provides 24/7 emergency services for burst pipes, sewer backups, and all plumbing issues.', '24/7 Emergency Plumbing in Ponce | Apex Plumbing', 'Expert emergency plumbing services in Ponce. 24/7 availability for burst pipes, sewer line backups, and all plumbing emergencies. Call now for rapid response.', true);

-- Create a function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_cities_data_updated_at
  BEFORE UPDATE ON cities_data
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
