// ============================================================
// PLATFORM DEFINITIONS
// Each platform has: URL, field selectors, description preference,
// pause points, and special instructions.
// ============================================================

export const platforms = [
  // ── HIGH PRIORITY ──────────────────────────────────────
  {
    id: 'crunchbase',
    name: 'Crunchbase',
    priority: 1,
    url: 'https://www.crunchbase.com/register',
    signupUrl: 'https://www.crunchbase.com/register',
    addBusinessUrl: 'https://www.crunchbase.com/discover/organizations',
    descriptionPref: 'A',
    descriptionLength: 'long',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and CAPTCHA if prompted' },
      { after: 'login', reason: 'After login, click "Add Profile" → "Company" to begin listing' },
    ],
    fields: {
      // Selectors are best-effort; Crunchbase uses dynamic React components
      companyName: { selector: 'input[name="name"], input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], input[placeholder*="website"]', type: 'url' },
      description: { selector: 'textarea[name="description"], textarea[placeholder*="description"]', type: 'textarea' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services, Plumbing, Consumer Services',
    notes: 'Register with yohomefix@gmail.com. After email verification, search for YoHomeFix. If not found, create new company profile. Connect LinkedIn for trust score.',
    skipIf: [],
  },
  {
    id: 'trustpilot',
    name: 'Trustpilot',
    priority: 2,
    url: 'https://businessapp.b2c.trustpilot.com/signup',
    signupUrl: 'https://businessapp.b2c.trustpilot.com/signup',
    addBusinessUrl: 'https://businessapp.b2c.trustpilot.com/signup',
    descriptionPref: 'B',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
      { after: 'domain_claim', reason: 'Verify domain ownership via DNS or meta tag' },
    ],
    fields: {
      companyName: { selector: 'input[name="name"], input[placeholder*="business name"]', type: 'text' },
      website: { selector: 'input[name="website"], input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services / Plumbing',
    notes: 'Free business account. Domain verification required for claiming. Add Trustpilot widget to yohomefix.com after approval.',
    skipIf: [],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Company Page',
    priority: 3,
    url: 'https://www.linkedin.com/company/setup/new/',
    signupUrl: 'https://www.linkedin.com/login',
    addBusinessUrl: 'https://www.linkedin.com/company/setup/new/',
    descriptionPref: 'C',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'login', reason: 'Log in with your personal LinkedIn account' },
      { after: 'page_creation', reason: 'Verify page via LinkedIn confirmation email' },
    ],
    fields: {
      companyName: { selector: 'input[name="name"], input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], input[placeholder*="website"]', type: 'url' },
      description: { selector: 'textarea[name="description"], textarea[placeholder*="description"]', type: 'textarea' },
    },
    category: 'Consumer Services / Home Services',
    notes: 'Requires personal LinkedIn account first. Set specialties: Emergency Plumbing, Home Services, Plumbing Dispatch.',
    skipIf: [],
  },
  {
    id: 'facebook',
    name: 'Facebook Business Page',
    priority: 4,
    url: 'https://www.facebook.com/pages/create',
    signupUrl: 'https://www.facebook.com/login',
    addBusinessUrl: 'https://www.facebook.com/pages/create',
    descriptionPref: 'D',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'login', reason: 'Log in with your Facebook account' },
    ],
    fields: {
      pageName: { selector: 'input[placeholder*="Page name"], input[name="page_name"]', type: 'text' },
      category: { selector: 'input[placeholder*="Category"], input[name="category"]', type: 'text' },
      description: { selector: 'textarea[name="description"], textarea[placeholder*="description"]', type: 'textarea' },
      website: { selector: 'input[name="website"], input[placeholder*="website"]', type: 'url' },
    },
    category: 'Home Improvement / Plumbing Service',
    notes: 'Select "Business or Brand". Set "Visit Website" button as primary CTA. Do NOT add phone number.',
    skipIf: [],
  },

  // ── GENERAL DIRECTORIES ────────────────────────────────
  {
    id: 'manta',
    name: 'Manta',
    priority: 5,
    url: 'https://www.manta.com/mb/add-business',
    signupUrl: 'https://www.manta.com/mb/add-business',
    addBusinessUrl: 'https://www.manta.com/mb/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA if present, then submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="business name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea[placeholder*="description"]', type: 'textarea' },
      category: { selector: 'input[name="category"], #category, input[placeholder*="category"]', type: 'text' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing. Set service area to National/United States.',
    skipIf: [],
  },
  {
    id: 'hotfrog',
    name: 'Hotfrog',
    priority: 6,
    url: 'https://www.hotfrog.com/company/add',
    signupUrl: 'https://www.hotfrog.com/company/add',
    addBusinessUrl: 'https://www.hotfrog.com/company/add',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA if present, then submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'brownbook',
    name: 'Brownbook',
    priority: 7,
    url: 'https://www.brownbook.net',
    signupUrl: 'https://www.brownbook.net/register/',
    addBusinessUrl: 'https://www.brownbook.net/add-business/',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification, then search for "Add Business" button' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="url"], #url, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Register first, then add business. Free listing.',
    skipIf: [],
  },
  {
    id: 'cylex',
    name: 'Cylex',
    priority: 8,
    url: 'https://www.cylex.us',
    signupUrl: 'https://www.cylex.us/register.html',
    addBusinessUrl: 'https://www.cylex.us/add-company.html',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="companyName"], #companyName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing. US directory.',
    skipIf: [],
  },
  {
    id: 'ibegin',
    name: 'iBegin',
    priority: 9,
    url: 'https://www.ibegin.com',
    signupUrl: 'https://www.ibegin.com/register',
    addBusinessUrl: 'https://www.ibegin.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="url"], #url, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'showmelocal',
    name: 'ShowMeLocal',
    priority: 10,
    url: 'https://www.showmelocal.com/add-business',
    signupUrl: 'https://www.showmelocal.com/add-business',
    addBusinessUrl: 'https://www.showmelocal.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA if present, then submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'tupalo',
    name: 'Tupalo',
    priority: 11,
    url: 'https://www.tupalo.com',
    signupUrl: 'https://www.tupalo.com/register',
    addBusinessUrl: 'https://www.tupalo.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #url, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'mapquest',
    name: 'MapQuest',
    priority: 12,
    url: 'https://www.mapquest.com',
    signupUrl: 'https://www.mapquest.com/add-business',
    addBusinessUrl: 'https://www.mapquest.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete any verification and submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing. May redirect to Yext partner flow.',
    skipIf: [],
  },
  {
    id: 'openstreetmap',
    name: 'OpenStreetMap',
    priority: 13,
    url: 'https://www.openstreetmap.org',
    signupUrl: 'https://www.openstreetmap.org/user/new',
    addBusinessUrl: 'https://www.openstreetmap.org/edit',
    descriptionPref: 'E',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification, then open the iD editor to add business node' },
      { after: 'map_loaded', reason: 'Manually place your business on the map, then script will fill details' },
    ],
    fields: {
      name: { selector: 'input[name="name"], input[placeholder*="Name"]', type: 'text' },
      website: { selector: 'input[name="website"], input[placeholder*="Website"]', type: 'url' },
      description: { selector: 'input[name="description"], textarea[name="description"]', type: 'text' },
    },
    category: 'Plumbing Services',
    notes: 'Open data platform. Add as a POI/node. Changes go live after community review.',
    skipIf: [],
  },
  {
    id: 'foursquare',
    name: 'Foursquare',
    priority: 14,
    url: 'https://foursquare.com',
    signupUrl: 'https://foursquare.com/business',
    addBusinessUrl: 'https://foursquare.com/business/claim',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email/phone verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Service',
    notes: 'Claim or add business. May require postcard verification for address.',
    skipIf: ['no_address'],
  },
  {
    id: 'yp',
    name: 'Yellow Pages (YP.com)',
    priority: 15,
    url: 'https://www.yellowpages.com',
    signupUrl: 'https://www.yellowpages.com/add-business',
    addBusinessUrl: 'https://www.yellowpages.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA and submit. Free listing only — do not pay.' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services / Emergency Plumbing',
    notes: 'Free basic listing only. Do NOT pay for premium.',
    skipIf: [],
  },
  {
    id: 'superpages',
    name: 'Superpages',
    priority: 16,
    url: 'https://www.superpages.com',
    signupUrl: 'https://www.superpages.com/add-business',
    addBusinessUrl: 'https://www.superpages.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA and submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'merchantcircle',
    name: 'MerchantCircle',
    priority: 17,
    url: 'https://www.merchantcircle.com',
    signupUrl: 'https://www.merchantcircle.com/signup',
    addBusinessUrl: 'https://www.merchantcircle.com/signup',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'citysearch',
    name: 'Citysearch',
    priority: 18,
    url: 'https://www.citysearch.com',
    signupUrl: 'https://www.citysearch.com/add-business',
    addBusinessUrl: 'https://www.citysearch.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA and submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing. May redirect to Citygrid Media.',
    skipIf: [],
  },
  {
    id: 'usdirectory',
    name: 'USDirectory',
    priority: 19,
    url: 'https://www.usdirectory.com',
    signupUrl: 'https://www.usdirectory.com/add-business',
    addBusinessUrl: 'https://www.usdirectory.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete CAPTCHA and submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'ezlocal',
    name: 'EZLocal',
    priority: 20,
    url: 'https://www.ezlocal.com',
    signupUrl: 'https://www.ezlocal.com/add-business',
    addBusinessUrl: 'https://www.ezlocal.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete and submit. Free listing only.' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing. May upsell paid features — skip those.',
    skipIf: [],
  },
  {
    id: 'localstack',
    name: 'LocalStack',
    priority: 21,
    url: 'https://www.localstack.com',
    signupUrl: 'https://www.localstack.com/add-business',
    addBusinessUrl: 'https://www.localstack.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete and submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },
  {
    id: 'n49',
    name: 'n49',
    priority: 22,
    url: 'https://www.n49.com',
    signupUrl: 'https://www.n49.com/add-business',
    addBusinessUrl: 'https://www.n49.com/add-business',
    descriptionPref: 'E',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: false,
    pausePoints: [
      { after: 'form_fill', reason: 'Complete and submit' },
    ],
    fields: {
      businessName: { selector: 'input[name="businessName"], #businessName, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing Services',
    notes: 'Free listing.',
    skipIf: [],
  },

  // ── HOME SERVICE DIRECTORIES ───────────────────────────
  {
    id: 'bark',
    name: 'Bark.com',
    priority: 23,
    url: 'https://www.bark.com',
    signupUrl: 'https://www.bark.com/en/us/business-signup/',
    addBusinessUrl: 'https://www.bark.com/en/us/business-signup/',
    descriptionPref: 'G',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and profile setup' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
      description: { selector: 'textarea[name="description"], #description, textarea', type: 'textarea' },
    },
    category: 'Plumbing',
    notes: 'Free profile. Home services marketplace.',
    skipIf: [],
  },
  {
    id: 'porch',
    name: 'Porch',
    priority: 24,
    url: 'https://porch.com',
    signupUrl: 'https://porch.com/pro',
    addBusinessUrl: 'https://porch.com/pro',
    descriptionPref: 'G',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and professional profile setup' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing',
    notes: 'Free professional profile.',
    skipIf: [],
  },
  {
    id: 'networx',
    name: 'Networx',
    priority: 25,
    url: 'https://www.networx.com',
    signupUrl: 'https://www.networx.com/pro',
    addBusinessUrl: 'https://www.networx.com/pro',
    descriptionPref: 'G',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing',
    notes: 'Free profile. Contractor directory.',
    skipIf: [],
  },
  {
    id: 'buildzoom',
    name: 'BuildZoom',
    priority: 26,
    url: 'https://www.buildzoom.com',
    signupUrl: 'https://www.buildzoom.com/contractor-signup',
    addBusinessUrl: 'https://www.buildzoom.com/contractor-signup',
    descriptionPref: 'G',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and contractor profile setup' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Plumbing',
    notes: 'Free contractor profile. May require license number.',
    skipIf: [],
  },

  // ── REVIEW / TRUST PLATFORMS ───────────────────────────
  {
    id: 'sitejabber',
    name: 'Sitejabber',
    priority: 27,
    url: 'https://www.sitejabber.com',
    signupUrl: 'https://www.sitejabber.com/business',
    addBusinessUrl: 'https://www.sitejabber.com/business',
    descriptionPref: 'B',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and domain claim' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], #email, input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Free business profile. Domain verification required.',
    skipIf: [],
  },

  // ── SOCIAL / COMMUNITY ─────────────────────────────────
  {
    id: 'instagram',
    name: 'Instagram',
    priority: 28,
    url: 'https://www.instagram.com',
    signupUrl: 'https://www.instagram.com/accounts/emailsignup/',
    addBusinessUrl: 'https://www.instagram.com/accounts/emailsignup/',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email/SMS verification, then switch to Business account' },
    ],
    fields: {
      fullName: { selector: 'input[name="fullName"], input[placeholder*="Full Name"]', type: 'text' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Create account, then switch to Business in Settings. Link to Facebook Page.',
    skipIf: [],
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    priority: 29,
    url: 'https://x.com',
    signupUrl: 'https://x.com/i/flow/signup',
    addBusinessUrl: 'https://x.com/i/flow/signup',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email/phone verification' },
    ],
    fields: {
      name: { selector: 'input[name="name"], input[placeholder*="name"]', type: 'text' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Create account, add website in profile settings.',
    skipIf: [],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    priority: 30,
    url: 'https://www.youtube.com',
    signupUrl: 'https://accounts.google.com/signup',
    addBusinessUrl: 'https://www.youtube.com/create_channel',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete Google account creation and phone verification' },
    ],
    fields: {
      name: { selector: 'input[name="name"], input[placeholder*="name"]', type: 'text' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Requires Google account. Create channel after login.',
    skipIf: [],
  },
  {
    id: 'pinterest',
    name: 'Pinterest Business',
    priority: 31,
    url: 'https://business.pinterest.com',
    signupUrl: 'https://www.pinterest.com/business/create/',
    addBusinessUrl: 'https://www.pinterest.com/business/create/',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and website claim' },
    ],
    fields: {
      businessName: { selector: 'input[name="business_name"], input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], input[placeholder*="website"]', type: 'url' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Improvement',
    notes: 'Business account. Verify website via meta tag.',
    skipIf: [],
  },
  {
    id: 'medium',
    name: 'Medium',
    priority: 32,
    url: 'https://medium.com',
    signupUrl: 'https://medium.com/m/signin',
    addBusinessUrl: 'https://medium.com/m/signin',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification' },
    ],
    fields: {
      name: { selector: 'input[name="name"], input[placeholder*="name"]', type: 'text' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Create profile, add website in bio. Publish plumbing tips articles.',
    skipIf: [],
  },
  {
    id: 'quora',
    name: 'Quora',
    priority: 33,
    url: 'https://www.quora.com',
    signupUrl: 'https://www.quora.com',
    addBusinessUrl: 'https://www.quora.com',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email verification and profile setup' },
    ],
    fields: {
      name: { selector: 'input[name="name"], input[placeholder*="name"]', type: 'text' },
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Create profile with credentials. Answer plumbing questions.',
    skipIf: [],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    priority: 34,
    url: 'https://www.reddit.com',
    signupUrl: 'https://www.reddit.com/register',
    addBusinessUrl: 'https://www.reddit.com/register',
    descriptionPref: 'F',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete email/username verification' },
    ],
    fields: {
      email: { selector: 'input[name="email"], input[type="email"]', type: 'email' },
    },
    category: 'Home Services',
    notes: 'Create brand account. Participate in r/HomeImprovement, r/Plumbing helpfully.',
    skipIf: [],
  },
  {
    id: 'glassdoor',
    name: 'Glassdoor',
    priority: 35,
    url: 'https://www.glassdoor.com',
    signupUrl: 'https://www.glassdoor.com/employers',
    addBusinessUrl: 'https://www.glassdoor.com/employers',
    descriptionPref: 'C',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete employer email verification' },
    ],
    fields: {
      companyName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
    },
    category: 'Consumer Services / Home Services',
    notes: 'Employer profile. Free.',
    skipIf: [],
  },
  {
    id: 'nextdoor',
    name: 'Nextdoor Business',
    priority: 36,
    url: 'https://business.nextdoor.com',
    signupUrl: 'https://business.nextdoor.com',
    addBusinessUrl: 'https://business.nextdoor.com',
    descriptionPref: 'D',
    descriptionLength: 'medium',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'signup', reason: 'Complete business verification' },
    ],
    fields: {
      businessName: { selector: 'input[name="name"], #name, input[placeholder*="name"]', type: 'text' },
      website: { selector: 'input[name="website"], #website, input[placeholder*="website"]', type: 'url' },
    },
    category: 'Home Services / Plumbing',
    notes: 'Business page. Free.',
    skipIf: [],
  },

  // ── CRAIGSLIST (special handling) ──────────────────────
  {
    id: 'craigslist',
    name: 'Craigslist',
    priority: 0, // Highest priority — run first
    url: 'https://www.craigslist.org',
    signupUrl: 'https://accounts.craigslist.org/login/home',
    addBusinessUrl: 'https://post.craigslist.org/c/str',
    descriptionPref: 'D',
    descriptionLength: 'short',
    landingPage: 'default',
    useShortUrl: false,
    requiresLogin: true,
    pausePoints: [
      { after: 'login', reason: 'Log in with your Craigslist account (requires phone-verified account)' },
      { after: 'category_select', reason: 'Select "Services" → "household" or "labor/move" category' },
      { after: 'area_select', reason: 'Select the posting area/metro' },
      { after: 'form_fill', reason: 'Review the post, complete CAPTCHA, and publish' },
    ],
    fields: {
      postingTitle: { selector: 'input[name="PostingTitle"], #PostingTitle, input[placeholder*="title"]', type: 'text' },
      body: { selector: 'textarea[name="PostingBody"], #PostingBody, textarea', type: 'textarea' },
      email: { selector: 'input[name="FromEMail"], #FromEMail, input[type="email"]', type: 'email' },
    },
    category: 'Services → Household',
    notes: 'Requires phone-verified Craigslist account. Post in major metros: NYC, LA, Chicago, Houston, Phoenix, Philadelphia, San Antonio, Dallas, San Diego, Austin. Use short description. Include website link in body.',
    craigslistAreas: [
      'https://newyork.craigslist.org',
      'https://losangeles.craigslist.org',
      'https://chicago.craigslist.org',
      'https://houston.craigslist.org',
      'https://phoenix.craigslist.org',
      'https://philadelphia.craigslist.org',
      'https://sanantonio.craigslist.org',
      'https://dallas.craigslist.org',
      'https://sandiego.craigslist.org',
      'https://austin.craigslist.org',
    ],
    skipIf: [],
  },
];

// ============================================================
// EXCLUDED PLATFORMS — Never attempt these
// ============================================================

export const excludedPlatforms = [
  { id: 'google_business', name: 'Google Business Profile', reason: 'Lead-gen companies explicitly ineligible' },
  { id: 'yelp', name: 'Yelp', reason: 'Lead-gen companies explicitly excluded' },
  { id: 'angi', name: 'Angi', reason: 'Competitor platform, not a citation directory' },
  { id: 'thumbtack', name: 'Thumbtack', reason: 'Competitor platform, not a citation directory' },
];
