/**
 * Sprint #8 — External Distribution Package
 *
 * Pre-prepared metadata for submitting the YoHomeFix Water Hardness
 * & Plumbing Risk Index to external platforms.
 *
 * Each platform entry contains:
 * - classification: A/B/C/D
 * - status: PREPARED / SUBMITTED / PUBLISHED
 * - accountRequired: boolean
 * - accountUrl: where to create account
 * - submissionProcess: step-by-step
 * - preparedMetadata: title, description, keywords, citation, license
 * - filesToUpload: exact files from dist/
 */

export const DISTRIBUTION_PACKAGE = {
  title: 'US City Water Hardness & Plumbing Risk Index',
  publisher: 'YoHomeFix',
  publisherUrl: 'https://yohomefix.com',
  sourceUrl: 'https://yohomefix.com/research/us-water-hardness-plumbing-risk',
  license: 'CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)',
  licenseNote: 'Covers YoHomeFix compilation, classifications, and risk scoring. Underlying factual measurements from public sources are not subject to this license.',
  citation: 'YoHomeFix. (2026). US City Water Hardness & Plumbing Risk Index. Retrieved from https://yohomefix.com/research/us-water-hardness-plumbing-risk',
  keywords: ['water hardness', 'plumbing risk', 'US cities', 'CaCO3', 'water quality', 'pipe infrastructure', 'municipal water', 'hard water', 'plumbing', 'home improvement'],
  filesToUpload: [
    'dist/yohomefix-water-hardness-plumbing-risk-index.csv',
    'dist/README.md',
  ],
  description: 'Water hardness measurements (mg/L CaCO3) and plumbing infrastructure risk scores for 155 US cities. Compiled from publicly available municipal water quality reports, utility Consumer Confidence Reports, and the USGS water hardness database, with YoHomeFix plumbing infrastructure assessments and composite risk scoring. 17 variables per city including hardness class, infrastructure age, winter risk, pipe material, sewer system, soil type, and computed plumbing risk scores (range 3-10). Provenance is tiered: 18 cities verified against primary utility CCRs (Tier A), remaining values compiled from public databases (Tier B) or estimated from regional geology (Tier C).',
};

export const PLATFORMS = [
  {
    name: 'Zenodo',
    url: 'https://zenodo.org',
    classification: 'A — HIGH-VALUE',
    status: 'PREPARED',
    accountRequired: true,
    accountUrl: 'https://zenodo.org/signup/',
    accountMethods: ['Email', 'GitHub', 'ORCID', 'OpenAIRE'],
    cost: 'Free',
    acceptsCommercial: true,
    publicCrawlablePage: true,
    outboundLinksAllowed: true,
    manualApproval: false,
    submissionProcess: [
      '1. Create account at https://zenodo.org/signup/ (or sign in with GitHub/ORCID)',
      '2. Click "+" in top-right → "New upload"',
      '3. Upload dist/yohomefix-water-hardness-plumbing-risk-index.csv and dist/README.md',
      '4. Set Resource type: Dataset',
      '5. Set Title: "US City Water Hardness & Plumbing Risk Index"',
      '6. Set Description: (use DISTRIBUTION_PACKAGE.description)',
      '7. Add Keywords: water hardness, plumbing risk, US cities, water quality, pipe infrastructure',
      '8. Set License: CC-BY 4.0',
      '9. Add Creator: YoHomeFix (organization)',
      '10. Set Publisher: YoHomeFix',
      '11. Add Related identifier: https://yohomefix.com/research/us-water-hardness-plumbing-risk (URL)',
      '12. Click "Publish"',
    ],
    expectedBenefit: 'Citable DOI, indexed by DataCite, discoverable via Google Scholar and open data catalogs. Public landing page with backlink to yohomefix.com.',
    preparedMetadata: {
      resourceType: 'Dataset',
      title: DISTRIBUTION_PACKAGE.title,
      description: DISTRIBUTION_PACKAGE.description,
      keywords: DISTRIBUTION_PACKAGE.keywords,
      license: 'CC-BY-4.0',
      creator: 'YoHomeFix',
      publisher: 'YoHomeFix',
      relatedIdentifier: DISTRIBUTION_PACKAGE.sourceUrl,
      publicationDate: '2026-07-23',
    },
  },
  {
    name: 'Kaggle',
    url: 'https://www.kaggle.com',
    classification: 'A — HIGH-VALUE',
    status: 'PREPARED',
    accountRequired: true,
    accountUrl: 'https://www.kaggle.com/account/login',
    accountMethods: ['Email', 'Google', 'Facebook'],
    cost: 'Free',
    acceptsCommercial: true,
    publicCrawlablePage: true,
    outboundLinksAllowed: true,
    manualApproval: false,
    phoneVerificationRequired: true,
    submissionProcess: [
      '1. Create account at https://www.kaggle.com/account/login',
      '2. Verify phone number (required for dataset uploads)',
      '3. Navigate to Datasets → New Dataset',
      '4. Upload dist/yohomefix-water-hardness-plumbing-risk-index.csv',
      '5. Set Title: "US City Water Hardness & Plumbing Risk Index"',
      '6. Set URL slug: yohomefix-water-hardness-plumbing-risk-index',
      '7. Set Description: (use DISTRIBUTION_PACKAGE.description + methodology from README)',
      '8. Set License: CC BY 4.0',
      '9. Set Visibility: Public',
      '10. Click "Create Dataset"',
    ],
    expectedBenefit: 'Public dataset page indexed by Google, discoverable by data scientists and researchers. Kaggle datasets rank well in search results. Backlink to source URL in description.',
    preparedMetadata: {
      title: DISTRIBUTION_PACKAGE.title,
      slug: 'yohomefix-water-hardness-plumbing-risk-index',
      description: DISTRIBUTION_PACKAGE.description,
      license: 'CC BY 4.0',
      visibility: 'Public',
      tags: ['water', 'public health', 'environment', 'home improvement'],
    },
  },
  {
    name: 'Hugging Face Datasets',
    url: 'https://huggingface.co/datasets',
    classification: 'B — USEFUL',
    status: 'PREPARED',
    accountRequired: true,
    accountUrl: 'https://huggingface.co/join',
    accountMethods: ['Email', 'GitHub', 'Google'],
    cost: 'Free',
    acceptsCommercial: true,
    publicCrawlablePage: true,
    outboundLinksAllowed: true,
    manualApproval: false,
    submissionProcess: [
      '1. Create account at https://huggingface.co/join',
      '2. Click profile → New Dataset',
      '3. Set name: yohomefix-water-hardness-plumbing-risk-index',
      '4. Set visibility: Public',
      '5. Upload dist/yohomefix-water-hardness-plumbing-risk-index.csv',
      '6. Create dataset card (README.md) with description, license, citation',
      '7. Set license: cc-by-4.0',
      '8. Publish',
    ],
    expectedBenefit: 'Public dataset page with Dataset Viewer. Indexed by Google. Popular in ML/data science community. Backlink in dataset card.',
    preparedMetadata: {
      title: DISTRIBUTION_PACKAGE.title,
      license: 'cc-by-4.0',
      description: DISTRIBUTION_PACKAGE.description,
      citation: DISTRIBUTION_PACKAGE.citation,
    },
  },
  {
    name: 'data.world',
    url: 'https://data.world',
    classification: 'B — USEFUL',
    status: 'PREPARED',
    accountRequired: true,
    accountUrl: 'https://data.world/user/create',
    accountMethods: ['Email', 'Google', 'GitHub'],
    cost: 'Free tier available',
    acceptsCommercial: true,
    publicCrawlablePage: true,
    outboundLinksAllowed: true,
    manualApproval: false,
    submissionProcess: [
      '1. Create account at https://data.world/user/create',
      '2. Create new dataset',
      '3. Set Title: "US City Water Hardness & Plumbing Risk Index"',
      '4. Set Description and Summary',
      '5. Set License: CC-BY',
      '6. Set Visibility: OPEN',
      '7. Upload dist/yohomefix-water-hardness-plumbing-risk-index.csv',
      '8. Add tags: water hardness, plumbing, water quality, US cities',
      '9. Publish',
    ],
    expectedBenefit: 'Public dataset page indexed by Google. data.world has good domain authority. Backlink in dataset description.',
    preparedMetadata: {
      title: DISTRIBUTION_PACKAGE.title,
      description: 'Water hardness and plumbing risk scores for 155 US cities.',
      summary: DISTRIBUTION_PACKAGE.description,
      license: 'CC-BY',
      visibility: 'OPEN',
      tags: ['water hardness', 'plumbing', 'water quality', 'US cities'],
    },
  },
  {
    name: 'HARO (Help a Reporter Out)',
    url: 'https://helpareporter.com',
    classification: 'A — HIGH-VALUE',
    status: 'PREPARED (monitoring required)',
    accountRequired: true,
    accountUrl: 'https://helpareporter.com',
    accountMethods: ['Email'],
    cost: 'Free',
    acceptsCommercial: true,
    publicCrawlablePage: false,
    outboundLinksAllowed: true,
    manualApproval: false,
    notes: 'HARO was relaunched April 2025 by Featured.com. Free 3x daily email digests of journalist queries. YoHomeFix should respond as a "homeowner research resource" and "plumbing data source" — NOT as a licensed plumbing contractor.',
    submissionProcess: [
      '1. Sign up at https://helpareporter.com with email',
      '2. Receive 3 daily email digests (Morning, Afternoon, Evening)',
      '3. Monitor for queries about: water quality, home maintenance, plumbing, hard water, water heaters, home improvement data',
      '4. Respond within 1 hour of digest arrival (critical for pickup)',
      '5. In response: identify as YoHomeFix research team, cite the water hardness dataset, provide data-driven insight from the research, link to https://yohomefix.com/research/us-water-hardness-plumbing-risk',
      '6. Do NOT use AI-generated responses (HARO now detects and rejects them)',
    ],
    expectedBenefit: 'Editorial mentions and backlinks from journalist articles on news sites. Each mention typically includes a dofollow or nofollow backlink.',
    expertPositioning: 'YoHomeFix as a nationwide homeowner connection and information platform with original research on US water hardness and plumbing risk.',
  },
  {
    name: 'Qwoted',
    url: 'https://qwoted.com',
    classification: 'B — USEFUL',
    status: 'PREPARED (monitoring required)',
    accountRequired: true,
    accountUrl: 'https://qwoted.com',
    accountMethods: ['Email'],
    cost: 'Free tier (2 pitches/month, 4h delay); $99/mo Pro',
    acceptsCommercial: true,
    publicCrawlablePage: false,
    outboundLinksAllowed: true,
    manualApproval: true,
    notes: 'Qwoted verifies expert profiles. 70%+ of queries come from DR 80+ publications. Free tier is limited but useful for occasional responses.',
    submissionProcess: [
      '1. Create account at https://qwoted.com',
      '2. Complete expert profile: identify as YoHomeFix research team',
      '3. Set expertise areas: home improvement, water quality, plumbing, consumer advocacy',
      '4. Monitor queries (free tier: 4h delay, 2 pitches/month)',
      '5. Respond to relevant queries with data from the water hardness research',
      '6. Link to https://yohomefix.com/research/us-water-hardness-plumbing-risk in responses',
    ],
    expectedBenefit: 'Backlinks from high-DR publications. Higher pickup rate than HARO (11.4% vs 6.8%).',
  },
  {
    name: 'Source of Sources (SOS)',
    url: 'https://sourceofsources.com',
    classification: 'C — LOW-VALUE',
    status: 'SKIP',
    reason: 'High spam volume (150 pitches per query), low pickup rate (3.2%), and uneven execution. Not worth the effort for YoHomeFix\'s use case.',
  },
  {
    name: 'Help a B2B Writer',
    url: 'https://helpab2bwriter.com',
    classification: 'D — UNSUITABLE',
    status: 'SKIP',
    reason: 'B2B-focused. YoHomeFix is a consumer/homeowner platform, not a B2B service. Query topics rarely match home services or water quality.',
  },
  {
    name: 'WaterHardness.org community submissions',
    url: 'https://www.waterhardness.org',
    classification: 'B — USEFUL',
    status: 'PREPARED',
    accountRequired: false,
    accountUrl: 'https://www.waterhardness.org/about/mission',
    cost: 'Free',
    acceptsCommercial: true,
    publicCrawlablePage: true,
    outboundLinksAllowed: false,
    manualApproval: true,
    notes: 'WaterHardness.org accepts community water hardness data submissions via their contact form. They review test method, location, and documentation before incorporating. This is a data contribution, not a backlink play — but being cited as a source builds authority.',
    submissionProcess: [
      '1. Go to https://www.waterhardness.org/about/mission',
      '2. Use the contact form (Message Type: "Submit Water Data")',
      '3. Submit YoHomeFix\'s Tier A verified data for 18 cities',
      '4. Reference the research page URL as source',
      '5. Note that YoHomeFix is a homeowner information platform with original water hardness research',
    ],
    expectedBenefit: 'Potential citation as data source on a high-authority water quality site. Not a direct backlink but builds research credibility.',
  },
  {
    name: 'GitHub (public repo mirror)',
    url: 'https://github.com',
    classification: 'A — HIGH-VALUE',
    status: 'PREPARED',
    accountRequired: true,
    accountUrl: 'https://github.com/signup',
    accountMethods: ['Email'],
    cost: 'Free',
    acceptsCommercial: true,
    publicCrawlablePage: true,
    outboundLinksAllowed: true,
    manualApproval: false,
    notes: 'Create a public GitHub repository mirroring the dataset. GitHub repos are indexed by Google and have high domain authority. Similar to the TapWaterData model (https://github.com/Tapwaterdata/water-hardness-dataset).',
    submissionProcess: [
      '1. Create GitHub account (or use existing: asimexports123)',
      '2. Create new public repository: yohomefix-water-hardness-dataset',
      '3. Upload dist/yohomefix-water-hardness-plumbing-risk-index.csv',
      '4. Upload dist/README.md as repository README',
      '5. Add repository description: "US water hardness and plumbing risk data for 155 cities"',
      '6. Add topics: water-hardness, water-quality, plumbing, public-health, open-data',
      '7. Set license: CC-BY-4.0',
      '8. Publish repository',
    ],
    expectedBenefit: 'Public GitHub repo indexed by Google. High DA backlink in README. Can be linked from Zenodo record. Discoverable by developers and researchers.',
    preparedMetadata: {
      repoName: 'yohomefix-water-hardness-dataset',
      description: 'US water hardness and plumbing risk data for 155 cities — CC BY 4.0',
      topics: ['water-hardness', 'water-quality', 'plumbing', 'public-health', 'open-data'],
      license: 'CC-BY-4.0',
    },
  },
];
