// ============================================================
// Sprint #6 — Organic Call Scoreboard
// Tracks GSC impression → CTR → call conversion pipeline
// for the 12 winner pages selected from GSC data analysis.
// ============================================================

export const WINNER_PAGES = [
  {
    slug: 'plumber-oklahoma-city-drain-cleaning',
    url: 'https://yohomefix.com/plumber-oklahoma-city-drain-cleaning',
    city: 'Oklahoma City',
    state: 'OK',
    service: 'drain-cleaning',
    impressions: 19292,
    clicks: 0,
    position: 29.48,
    ctr: 0,
    topQuery: 'emergency drain service',
    topQueryImpressions: 16300,
    bucket: 2,
    titleChange: 'Emergency Drain Cleaning → Emergency Drain Service',
    h1Change: 'Emergency Drain Cleaning → Emergency Drain Service',
    metaChange: 'No change needed (already says "drain service")',
    internalLinks: ['homepage drain cluster', 'OK state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P0',
  },
  {
    slug: 'plumber-baltimore-drain-cleaning',
    url: 'https://yohomefix.com/plumber-baltimore-drain-cleaning',
    city: 'Baltimore',
    state: 'MD',
    service: 'drain-cleaning',
    impressions: 5405,
    clicks: 0,
    position: 35.55,
    ctr: 0,
    topQuery: 'emergency drain service',
    topQueryImpressions: 16300,
    bucket: 2,
    titleChange: 'Emergency Drain Cleaning → Emergency Drain Service',
    h1Change: 'Emergency Drain Cleaning → Emergency Drain Service',
    metaChange: 'No change needed',
    internalLinks: ['homepage drain cluster', 'MD state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P0',
  },
  {
    slug: 'plumber-san-diego-emergency',
    url: 'https://yohomefix.com/plumber-san-diego-emergency',
    city: 'San Diego',
    state: 'CA',
    service: 'emergency',
    impressions: 1894,
    clicks: 0,
    position: 53.73,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change (already "Emergency Plumber in {city}")',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['homepage emergency cluster (NEW)', 'CA state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P1',
  },
  {
    slug: 'plumber-phoenix-emergency',
    url: 'https://yohomefix.com/plumber-phoenix-emergency',
    city: 'Phoenix',
    state: 'AZ',
    service: 'emergency',
    impressions: 1698,
    clicks: 0,
    position: 46.47,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['homepage emergency cluster', 'AZ state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P1',
  },
  {
    slug: 'plumber-san-antonio-emergency',
    url: 'https://yohomefix.com/plumber-san-antonio-emergency',
    city: 'San Antonio',
    state: 'TX',
    service: 'emergency',
    impressions: 1213,
    clicks: 0,
    position: 47.48,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['homepage emergency cluster', 'TX state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P1',
  },
  {
    slug: 'plumber-san-jose-emergency',
    url: 'https://yohomefix.com/plumber-san-jose-emergency',
    city: 'San Jose',
    state: 'CA',
    service: 'emergency',
    impressions: 971,
    clicks: 0,
    position: 53.72,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['homepage leak cluster (NEW)', 'CA state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P1',
  },
  {
    slug: 'plumber-sacramento-emergency',
    url: 'https://yohomefix.com/plumber-sacramento-emergency',
    city: 'Sacramento',
    state: 'CA',
    service: 'emergency',
    impressions: 920,
    clicks: 0,
    position: 49.64,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['CA state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P2',
  },
  {
    slug: 'plumber-cincinnati-emergency',
    url: 'https://yohomefix.com/plumber-cincinnati-emergency',
    city: 'Cincinnati',
    state: 'OH',
    service: 'emergency',
    impressions: 794,
    clicks: 0,
    position: 43.11,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['OH state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P2',
  },
  {
    slug: 'plumber-new-orleans-water-heater-repair',
    url: 'https://yohomefix.com/plumber-new-orleans-water-heater-repair',
    city: 'New Orleans',
    state: 'LA',
    service: 'water-heater-repair',
    impressions: 627,
    clicks: 1,
    position: 40.57,
    ctr: 0.16,
    topQuery: 'emergency hot water heater repair',
    topQueryImpressions: 338,
    bucket: 2,
    titleChange: 'Emergency Plumber → Water Heater Repair (lead with service keyword)',
    h1Change: 'No change (H1 uses service shortName)',
    metaChange: 'Added "emergency water heater repair" to description',
    internalLinks: ['homepage water heater cluster', 'LA state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P1',
    note: 'ONLY page with a click in GSC data — 1 click from 627 impressions',
  },
  {
    slug: 'plumber-milwaukee-emergency',
    url: 'https://yohomefix.com/plumber-milwaukee-emergency',
    city: 'Milwaukee',
    state: 'WI',
    service: 'emergency',
    impressions: 616,
    clicks: 0,
    position: 46.03,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['homepage drain cluster', 'WI state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P2',
  },
  {
    slug: 'plumber-baltimore-emergency',
    url: 'https://yohomefix.com/plumber-baltimore-emergency',
    city: 'Baltimore',
    state: 'MD',
    service: 'emergency',
    impressions: 571,
    clicks: 0,
    position: 33.6,
    ctr: 0,
    topQuery: 'emergency plumber',
    topQueryImpressions: 3189,
    bucket: 2,
    titleChange: 'Added "24 Hour Plumber" to title suffix',
    h1Change: 'No change',
    metaChange: 'Added "24 hour plumber" to description',
    internalLinks: ['MD state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P2',
  },
  {
    slug: 'plumber-kansas-city-drain-cleaning',
    url: 'https://yohomefix.com/plumber-kansas-city-drain-cleaning',
    city: 'Kansas City',
    state: 'MO',
    service: 'drain-cleaning',
    impressions: 330,
    clicks: 0,
    position: 30.67,
    ctr: 0,
    topQuery: 'emergency drain service',
    topQueryImpressions: 16300,
    bucket: 2,
    titleChange: 'Emergency Drain Cleaning → Emergency Drain Service',
    h1Change: 'Emergency Drain Cleaning → Emergency Drain Service',
    metaChange: 'No change needed',
    internalLinks: ['homepage drain cluster', 'MO state hub', 'nearby cities block'],
    callTrackingLabels: ['hero', 'mid-page', 'bottom', 'sticky-mobile', 'secondary-cta', 'secondary-cta-sms', 'exit-intent', 'quote-form'],
    priority: 'P2',
  },
];

// Summary stats
export const SCOREBOARD_SUMMARY = {
  totalWinners: WINNER_PAGES.length,
  totalImpressions: WINNER_PAGES.reduce((sum, p) => sum + p.impressions, 0),
  totalClicks: WINNER_PAGES.reduce((sum, p) => sum + p.clicks, 0),
  avgPosition: (WINNER_PAGES.reduce((sum, p) => sum + p.position, 0) / WINNER_PAGES.length).toFixed(2),
  marketcallCampaign: '348734',
  marketcallSite: '3143',
  marketcallPhone: '(844) 934-4386',
  marketcallPhoneE164: '+18449344386',
  changesImplemented: [
    'Drain cleaning title/H1: "Drain Cleaning" → "Drain Service" (matches 16,300-impression query)',
    'Emergency title suffix: "24/7 Licensed Service" → "24 Hour Plumber & Plumbing Service" (matches 770-impression query)',
    'Water heater repair title: "Emergency Plumber — Water Heater Repair" → "Water Heater Repair — Emergency 24/7 Service" (lead with service keyword)',
    'Emergency meta description: Added "24 hour plumber" keyword',
    'Water heater meta description: Added "emergency water heater repair" keyword',
    'Homepage title: "24/7 Local Plumbing Service" → "24 Hour Plumbing Service"',
    'State hub title: "24/7 Licensed Service" → "24 Hour Plumbing Service"',
    'Homepage drain section heading: "Drain Cleaning by City" → "Emergency Drain Service by City"',
    'Homepage drain link anchor: state code → "Drain Service" with descriptive title attr',
    'Homepage emergency cluster: Replaced San Jose with San Diego (1,894 imps)',
    'Homepage leak cluster: Replaced San Diego with San Jose (971 emergency imps)',
  ],
};

// Cannibalization audit results
export const CANNIBALIZATION_AUDIT = {
  findings: [
    {
      pages: ['plumber-oklahoma-city-drain-cleaning (19,292 imps, pos 29.48)', 'plumber-oklahoma (1,254 imps, pos 98.71)'],
      issue: 'OK state hub page ranking for drain-related queries at pos 98.71 — minimal cannibalization risk since state hub is at position 98+',
      action: 'No action needed — state hub is too deep to cannibalize',
    },
    {
      pages: ['plumber-oklahoma-city-drain-cleaning (19,292 imps)', 'plumber-oklahoma-city-emergency (124 imps, pos 49.47)'],
      issue: 'Different service pages — no cannibalization',
      action: 'No action needed',
    },
    {
      pages: ['plumber-baltimore-drain-cleaning (5,405 imps)', 'plumber-baltimore-emergency (571 imps)'],
      issue: 'Different service pages — no cannibalization',
      action: 'No action needed',
    },
  ],
  conclusion: 'No significant cannibalization detected among winner pages. State hub pages are too deep in positions to compete with city-service pages.',
};

// ============================================================
// Sprint #7 — Ranking Movement Tracker Baseline
// Records pre-Sprint-7 GSC positions for primary and secondary
// targets. Compare after 2-4 weeks post-deploy to measure
// authority concentration impact.
// ============================================================

export const SPRINT7_TARGETS = [
  {
    rank: 'primary',
    slug: 'plumber-oklahoma-city-drain-cleaning',
    url: 'https://yohomefix.com/plumber-oklahoma-city-drain-cleaning',
    city: 'Oklahoma City',
    state: 'OK',
    service: 'drain-cleaning',
    gscImpressions: 19292,
    gscClicks: 0,
    gscPosition: 29.48,
    gscCtr: 0,
    topQueries: [
      { query: 'emergency drain service', impressions: 16300, position: 28.5 },
      { query: 'emergency drain service oklahoma city', impressions: 210, position: 35.2 },
      { query: 'drain cleaning oklahoma city', impressions: 180, position: 42.1 },
    ],
    sprint7Actions: [
      'RelatedServiceCallout: emergency + sewer line cross-links added in-body',
      'Homepage drain cluster link already present (Sprint #6)',
      'State×service hub already links via city card',
      'RelatedGuides: hard water effects + signs you need a plumber',
    ],
    baselineDate: '2026-07-23',
  },
  {
    rank: 'secondary-1',
    slug: 'plumber-baltimore-drain-cleaning',
    url: 'https://yohomefix.com/plumber-baltimore-drain-cleaning',
    city: 'Baltimore',
    state: 'MD',
    service: 'drain-cleaning',
    gscImpressions: 5405,
    gscClicks: 0,
    gscPosition: 35.55,
    gscCtr: 0,
    topQueries: [
      { query: 'emergency drain service', impressions: 16300, position: 38.0 },
      { query: 'drain cleaning baltimore', impressions: 120, position: 45.3 },
    ],
    sprint7Actions: [
      'RelatedServiceCallout: emergency + sewer line cross-links added in-body',
      'Homepage drain cluster link already present (Sprint #6)',
    ],
    baselineDate: '2026-07-23',
  },
  {
    rank: 'secondary-2',
    slug: 'plumber-new-orleans-water-heater-repair',
    url: 'https://yohomefix.com/plumber-new-orleans-water-heater-repair',
    city: 'New Orleans',
    state: 'LA',
    service: 'water-heater-repair',
    gscImpressions: 817,
    gscClicks: 0,
    gscPosition: 46.67,
    gscCtr: 0,
    topQueries: [
      { query: 'emergency water heater repair', impressions: 880, position: 47.0 },
      { query: 'emergency hot water heater repair', impressions: 210, position: 49.5 },
    ],
    sprint7Actions: [
      'RelatedServiceCallout: emergency + leak repair cross-links added in-body',
      'Homepage water heater cluster link already present (Sprint #6)',
      'H1 already leads with "Water Heater Repair" (Sprint #6)',
    ],
    baselineDate: '2026-07-23',
  },
  {
    rank: 'secondary-3',
    slug: 'plumber-oklahoma-city-emergency',
    url: 'https://yohomefix.com/plumber-oklahoma-city-emergency',
    city: 'Oklahoma City',
    state: 'OK',
    service: 'emergency',
    gscImpressions: 124,
    gscClicks: 0,
    gscPosition: 49.47,
    gscCtr: 0,
    topQueries: [
      { query: 'emergency plumber oklahoma city', impressions: 70, position: 48.0 },
    ],
    sprint7Actions: [
      'RelatedServiceCallout: drain cleaning + water heater repair cross-links added in-body',
      'Receives authority from OKC drain cleaning page via contextual link',
    ],
    baselineDate: '2026-07-23',
  },
];

export const SPRINT7_SUMMARY = {
  sprint: 7,
  focus: 'Authority Concentration',
  baselineDate: '2026-07-23',
  totalTargets: SPRINT7_TARGETS.length,
  primaryTarget: 'plumber-oklahoma-city-drain-cleaning',
  primaryBaselinePosition: 29.48,
  primaryBaselineImpressions: 19292,
  implementedChanges: [
    'RelatedServiceCallout component: contextual in-body cross-links between related services on all city-service pages',
    'CSV download button added to water hardness research page',
    'Methodology section added to research page',
    'Editorial research finding (Sun Belt vs Northeast water hardness) added as news hook',
    'No title/H1/meta changes (Sprint #6 frozen)',
    'No Marketcall config changes',
    'No new pages created',
  ],
  externalActions: {
    completed: 0,
    pending: [
      'Zenodo dataset submission (requires ORCID account)',
      'HARO/Source of Sources signup (requires email)',
      'Featured.com expert submissions (requires account)',
      'RDL Hub dataset upload (requires account)',
    ],
  },
  backlinksAcquired: 0,
  callsGenerated: 'Not yet measurable — deploy pending',
  nextPage: 'Deploy build to production, then monitor GSC positions at 2-week and 4-week intervals',
};
