// ── Outreach Prospect Data Format ─────────────────────────────────
// This module defines the data structure for future AI-assisted
// digital PR outreach. No outreach is sent during this sprint.
//
// The schema is designed to be stored in a simple JSON file or
// database table and later consumed by an automation workflow.
//
// Sprint #5 Phase 5: All 50 original prospects reviewed and classified.
// 12 removed (C-grade), 8 new verified prospects added.
// Campaign segments: A=Data Story, B=Local City, C=Resource Update,
// D=Embeddable Tool, E=Expert/Reference

export const PROSPECT_SCHEMA = {
  fields: {
    id:               'string — unique identifier (slug)',
    domain:           'string — prospect website domain',
    siteName:         'string — publication or site name',
    relevantUrl:      'string — exact URL where research is relevant',
    contactName:      'string — publicly available contact name (if any)',
    contactEmail:     'string — public professional contact email (if any)',
    contactForm:      'string — URL of contact form (if no email)',
    opportunityType:  'enum — journalist | resource_page | local_data | article_update | embed_widget',
    grade:            'enum — A (Verified High-Value) | B (Verified Medium-Value) | C (Remove) | D (Needs Research)',
    campaignSegment:  'enum — A (Data Story) | B (Local City) | C (Resource Update) | D (Embeddable Tool) | E (Expert/Reference)',
    relevanceScore:   'integer 1-10 — how relevant the asset is to this prospect',
    priority:         'enum — high | medium | low',
    recommendedAngle: 'string — suggested outreach angle',
    targetAsset:      'string — YoHomeFix URL to promote',
    outreachStatus:   'enum — pending | contacted | responded | linked | declined | follow_up',
    lastContactDate:  'string ISO date — last outreach date',
    followUpDate:     'string ISO date — scheduled follow-up date',
    notes:            'string — additional context',
  },
};

// ── Removed Prospects (C-grade) ───────────────────────────────────
// epa-sdwis: Government site, will not link externally
// cdc-water: Government site, will not link externally
// energystar: Government site, will not link externally
// nrdc-water: Environmental org, tangential relevance
// iapmo: Code organization, unlikely to link externally
// pmm-magazine: UK plumbing magazine, irrelevant for US city data
// zillow: Real estate platform, no editorial content section for this
// redfin: Real estate blog, no water quality content
// water-env-federation: Professional org, low consumer relevance
// home-improvement-directory: Low-quality directory site
// hgtv: Broad lifestyle, no specific water quality content
// apartment-therapy: Broad lifestyle, low relevance
// plumbing-today: NOT a trade pub — verified as local plumbing company in Poughkeepsie NY

// ── Verified Prospect List ────────────────────────────────────────
// Legitimate prospects researched from public web presence.
// No private personal data. No scraped contacts. No automated submissions.
// These are publications and resources where the water hardness dataset
// provides genuine editorial value.

export const INITIAL_PROSPECTS = [
  // ═══ Campaign A: Data Story (journalists, data publishers) ═══
  { id: 'data-world', domain: 'data.world', siteName: 'data.world', relevantUrl: 'https://data.world/datasets/water', opportunityType: 'resource_page', grade: 'A', campaignSegment: 'A', relevanceScore: 9, priority: 'high', recommendedAngle: 'Open data platform — publish our CC BY 4.0 dataset with plumbing risk scores as a unique addition to their water data collection', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'CC BY 4.0 license makes this a natural fit. Our plumbing risk score is a differentiator vs other water hardness datasets.' },
  { id: 'kaggle', domain: 'kaggle.com', siteName: 'Kaggle', relevantUrl: 'https://www.kaggle.com/datasets?search=water+hardness', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'A', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Data science community — dataset with plumbing risk scores useful for water quality analysis projects', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Kaggle datasets can include external link references.' },
  { id: 'github-awesome-lists', domain: 'github.com', siteName: 'GitHub Awesome Public Datasets', relevantUrl: 'https://github.com/awesomedata/awesome-public-datasets', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'A', relevanceScore: 6, priority: 'medium', recommendedAngle: 'Curated dataset list — water quality data is a commonly requested category', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'PR submission via GitHub. Include link to research page in dataset description.' },
  { id: 'tapwaterdata', domain: 'tapwaterdata.com', siteName: 'TapWaterData', relevantUrl: 'https://www.tapwaterdata.com/water-hardness', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'A', relevanceScore: 8, priority: 'medium', recommendedAngle: 'They publish an open water hardness dataset (16,561 cities, CC BY 4.0) — our plumbing risk index is a complementary dataset they could reference or cross-link', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Not a direct competitor — they focus on hardness data only, we add plumbing risk scores. Potential for mutual citation. Has GitHub repo: Tapwaterdata/water-hardness-dataset' },
  { id: 'hardwaterhq', domain: 'hardwaterhq.com', siteName: 'HardWaterHQ', relevantUrl: 'https://hardwaterhq.com/water-quality/', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'A', relevanceScore: 7, priority: 'medium', recommendedAngle: 'They have 400+ city water hardness data — our plumbing risk index adds a dimension they do not cover', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Water quality site with city-level data. Plumbing risk angle is unique to us.' },

  // ═══ Campaign B: Local City Angle (local news in high/low hardness cities) ═══
  { id: 'arizona-daily-star', domain: 'tucson.com', siteName: 'Arizona Daily Star', relevantUrl: 'https://tucson.com/lifestyles/home-and-garden', opportunityType: 'local_data', grade: 'A', campaignSegment: 'B', relevanceScore: 10, priority: 'high', recommendedAngle: 'Tucson has the hardest water in our dataset at 344 mg/L — verified against Tucson Water official reports. Local data story for home & garden section about what this means for plumbing', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Tucson Water confirms hard to very hard classification. Strongest local angle.' },
  { id: 'bakersfield-californian', domain: 'bakersfield.com', siteName: 'The Bakersfield Californian', relevantUrl: 'https://www.bakersfield.com', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Bakersfield water is only moderately hard at 92 mg/L per Cal Water CCR — counterintuitive local story since many residents assume it is very hard', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Corrected from 335 to 92 mg/L. The surprise angle (residents think it is hard, but it is moderate) is a story hook.' },
  { id: 'phoenix-new-times', domain: 'phoenixnewtimes.com', siteName: 'Phoenix New Times', relevantUrl: 'https://www.phoenixnewtimes.com', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Phoenix metro cities (Mesa, Gilbert, Chandler) all at 250 mg/L — regional water quality and plumbing risk story', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Phoenix metro has consistently very hard water. Multiple cities in our dataset.' },
  { id: 'el-paso-times', domain: 'elpasotimes.com', siteName: 'El Paso Times', relevantUrl: 'https://www.elpasotimes.com', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 6, priority: 'medium', recommendedAngle: 'El Paso water hardness verified at 175 mg/L per El Paso Water — moderately hard, not as extreme as residents might think', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Corrected from 310 to 175 mg/L. Local angle: what does moderately hard water mean for plumbing?' },
  { id: 'inland-valley-daily-bulletin', domain: 'dailybulletin.com', siteName: 'Daily Bulletin (Inland Empire)', relevantUrl: 'https://www.dailybulletin.com', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 6, priority: 'medium', recommendedAngle: 'Riverside water hardness verified at 194 mg/L per Western MWD — local relevance for Inland Empire homeowners', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Corrected from 310 to 194 mg/L. Still hard water, good local angle.' },
  { id: 'seattle-times', domain: 'seattletimes.com', siteName: 'The Seattle Times', relevantUrl: 'https://www.seattletimes.com/life/lifestyle/home', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Seattle has very soft water at 22 mg/L — what this means for plumbing (soft water can be more corrosive to metal pipes)', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Corrected from 18 to 22 mg/L. Soft water corrosion angle is a lesser-known plumbing story.' },
  { id: 'portland-oregonian', domain: 'oregonlive.com', siteName: 'The Oregonian', relevantUrl: 'https://www.oregonlive.com/life-and-culture/home-garden', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Portland has very soft water at 11 mg/L per Portland Water Bureau — among the softest in the US', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Corrected from 18 to 11 mg/L. Bull Run supply is exceptionally soft.' },
  { id: 'boston-globe', domain: 'bostonglobe.com', siteName: 'The Boston Globe', relevantUrl: 'https://www.bostonglobe.com/lifestyle/home', opportunityType: 'local_data', grade: 'A', campaignSegment: 'B', relevanceScore: 8, priority: 'high', recommendedAngle: 'Boston has the softest water of any major US city in our dataset at 8 mg/L per MWRA — local story about what this means for plumbing and appliances', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'New prospect replacing C-grade. Boston is now #1 softest city. MWRA data verified at 8 mg/L.' },
  { id: 'san-diego-tribune', domain: 'sandiegouniontribune.com', siteName: 'San Diego Union-Tribune', relevantUrl: 'https://www.sandiegouniontribune.com/lifestyle/home-and-garden', opportunityType: 'local_data', grade: 'B', campaignSegment: 'B', relevanceScore: 7, priority: 'medium', recommendedAngle: 'San Diego water hardness verified at 237 mg/L per city CCR — hard water and its effect on plumbing in America Finest City', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'New prospect. Corrected from 291 to 237 mg/L. Still hard, good local angle.' },

  // ═══ Campaign C: Resource Update (existing articles that could link to our data) ═══
  { id: 'this-old-house', domain: 'thisoldhouse.com', siteName: 'This Old House', relevantUrl: 'https://www.thisoldhouse.com/water-heater/reviews', opportunityType: 'article_update', grade: 'A', campaignSegment: 'C', relevanceScore: 9, priority: 'high', recommendedAngle: 'Water hardness data complements their water heater and water softener content — offer the dataset as a reference resource with city-level specificity', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Major home improvement publisher. Strong editorial team. Water softener and water heater content is extensive.' },
  { id: 'bob-vila', domain: 'bobvila.com', siteName: 'Bob Vila', relevantUrl: 'https://www.bobvila.com/articles/water-softeners/', opportunityType: 'article_update', grade: 'A', campaignSegment: 'C', relevanceScore: 8, priority: 'high', recommendedAngle: 'Their water softener articles reference general hardness info — our city-level data with 18 verified values adds specificity and credibility', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Well-known home improvement brand. Water softener content is a natural fit.' },
  { id: 'family-handyman', domain: 'familyhandyman.com', siteName: 'Family Handyman', relevantUrl: 'https://www.familyhandyman.com/list/plumbing/', opportunityType: 'resource_page', grade: 'A', campaignSegment: 'C', relevanceScore: 8, priority: 'high', recommendedAngle: 'Plumbing section covers hard water issues — our original research with plumbing risk scores adds unique data value', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Major DIY publisher. Plumbing section is extensive.' },
  { id: 'consumer-reports-water', domain: 'consumerreports.org', siteName: 'Consumer Reports', relevantUrl: 'https://www.consumerreports.org/water-softeners/best-water-softeners-a1078947', opportunityType: 'article_update', grade: 'A', campaignSegment: 'C', relevanceScore: 8, priority: 'high', recommendedAngle: 'Water softener buying guide — city-level hardness data helps consumers determine if they need a softener. Our Tier A verified data adds credibility', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Major consumer publication. High authority. Water softener guide is a strong fit.' },
  { id: 'the-spruce', domain: 'thespruce.com', siteName: 'The Spruce', relevantUrl: 'https://www.thespruce.com/water-softener-buying-guide-4150660', opportunityType: 'article_update', grade: 'A', campaignSegment: 'C', relevanceScore: 8, priority: 'high', recommendedAngle: 'Water softener buying guide — hardness data helps readers decide if they need treatment. Link to our city lookup tool', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Major home content publisher. Water softener guide is a natural fit.' },
  { id: 'home-advisor', domain: 'homeadvisor.com', siteName: 'HomeAdvisor', relevantUrl: 'https://www.homeadvisor.com/cost/plumbing/', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'C', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Cost guide content could reference regional hardness differences that affect plumbing costs and maintenance frequency', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Major home services platform. Cost guides are a natural place for hardness context.' },
  { id: 'angi', domain: 'angi.com', siteName: 'Angi', relevantUrl: 'https://www.angi.com/articles/water-softener-installation.htm', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Water softener installation guide could benefit from city-specific hardness data to help homeowners decide if treatment is needed', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Major home services platform. Water softener content is relevant.' },
  { id: 'hunker', domain: 'hunker.com', siteName: 'Hunker', relevantUrl: 'https://www.hunker.com/13495114/how-to-tell-if-you-have-hard-water', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 6, priority: 'medium', recommendedAngle: 'Hard water identification article could link to city-level data so readers can check their city', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Home content site. Hard water article is directly relevant.' },
  { id: 'fixr', domain: 'fixr.com', siteName: 'Fixr', relevantUrl: 'https://www.fixr.com/costs/water-softener-installation', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Cost guide for water softener installation — hardness data helps consumers determine necessity by city', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Cost guide site. Water softener cost page is a natural fit.' },
  { id: 'improvenet', domain: 'improvenet.com', siteName: 'ImproveNet', relevantUrl: 'https://www.improvenet.com/cost/water-softener-installation-cost', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 6, priority: 'medium', recommendedAngle: 'Water softener cost guide — city hardness data supports cost-benefit analysis for homeowners', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Cost guide site. Similar to Fixr.' },
  { id: 'fresh-water-systems', domain: 'freshwatersystems.com', siteName: 'Fresh Water Systems', relevantUrl: 'https://www.freshwatersystems.com/articles', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Water treatment retailer — educational content can reference city-level hardness data with our verified Tier A sources', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Water treatment retailer with educational articles. Good fit for hardness data.' },
  { id: 'water-treatment-reviews', domain: 'watertreatmentreviews.com', siteName: 'Water Treatment Reviews', relevantUrl: 'https://www.watertreatmentreviews.com', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'C', relevanceScore: 6, priority: 'low', recommendedAngle: 'Water treatment review site — dataset adds objective data to product recommendations', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Review site. Needs verification of site quality and traffic.' },
  { id: 'aquasana', domain: 'aquasana.com', siteName: 'Aquasana', relevantUrl: 'https://www.aquasana.com/blog', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 6, priority: 'low', recommendedAngle: 'Water filtration brand blog — hardness data supports their educational content about when filtration is needed', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Water filtration brand. Blog content is educational. Lower priority but legitimate.' },
  { id: 'purewaterblog', domain: 'purewaterblog.com', siteName: 'Pure Water Blog', relevantUrl: 'https://purewaterblog.com/does-boston-have-hard-water/', opportunityType: 'article_update', grade: 'B', campaignSegment: 'C', relevanceScore: 7, priority: 'medium', recommendedAngle: 'They write city-specific water hardness articles (Boston, Seattle, etc.) — our dataset with verified Tier A values for those exact cities is a natural reference', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'New prospect. Writes detailed city-by-city water hardness blog posts. Already cites MWRA and waterhardness.org data.' },

  // ═══ Campaign D: Embeddable Tool (sites that could embed our widget) ═══
  { id: 'home-inspection-sites', domain: 'various', siteName: 'Home Inspection Company Websites', relevantUrl: 'various', opportunityType: 'embed_widget', grade: 'D', campaignSegment: 'D', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Home inspectors can embed the lookup for clients to check water hardness before buying. Identify specific inspection companies with resource pages', targetAsset: '/research/embed', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Needs specific company identification. General category — must find individual sites.' },

  // ═══ Campaign E: Expert/Reference Resource (authoritative sites that could cite our research) ═══
  { id: 'water-quality-association', domain: 'wqa.org', siteName: 'Water Quality Association', relevantUrl: 'https://www.wqa.org/find-water-treatment-professionals', opportunityType: 'resource_page', grade: 'A', campaignSegment: 'E', relevanceScore: 9, priority: 'high', recommendedAngle: 'Industry authority — offer the dataset as a consumer resource for understanding local hardness. Our Tier A verified data and plumbing risk index adds value beyond their existing resources', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Top industry authority. Consumer education section is a natural fit.' },
  { id: 'usgs-water-science', domain: 'usgs.gov', siteName: 'USGS Water Science School', relevantUrl: 'https://www.usgs.gov/special-topics/water-science-school/science/hardness-water', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'E', relevanceScore: 9, priority: 'medium', recommendedAngle: 'Our classification system aligns with their hardness scale — offer as a consumer-friendly companion resource with city-level data and plumbing risk context', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Authoritative source. Government site — unlikely to link externally, but if they have a resources section for educators it is possible.' },
  { id: 'nsf-water', domain: 'nsf.org', siteName: 'NSF International', relevantUrl: 'https://www.nsf.org/consumer-resources/water-quality', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'E', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Water quality certification body — consumer resources could reference city hardness data as context for treatment decisions', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Certification organization. Consumer resources section is relevant.' },
  { id: 'phcc', domain: 'phccweb.org', siteName: 'PHCC (Plumbing-Heating-Cooling Contractors)', relevantUrl: 'https://www.phccweb.org/resources', opportunityType: 'resource_page', grade: 'B', campaignSegment: 'E', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Trade association resource page — dataset provides consumer education value for members and their customers', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Trade association. Resources section is relevant for member education.' },
  { id: 'achr-news', domain: 'achrnews.com', siteName: 'ACHR News', relevantUrl: 'https://www.achrnews.com/topics/plumbing', opportunityType: 'journalist', grade: 'B', campaignSegment: 'E', relevanceScore: 7, priority: 'medium', recommendedAngle: 'HVAC/plumbing trade publication — data story about regional hardness affecting appliance life and plumbing service demand', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Trade publication. Plumbing section covers water quality topics.' },
  { id: 'supply-house-times', domain: 'supplyhousetimes.com', siteName: 'Supply House Times', relevantUrl: 'https://www.supplyhousetimes.com', opportunityType: 'journalist', grade: 'B', campaignSegment: 'E', relevanceScore: 6, priority: 'medium', recommendedAngle: 'Plumbing supply industry — hardness data informs product demand by region. Plumbing risk index helps distributors understand regional service patterns', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'Plumbing supply trade publication. Regional data angle is relevant.' },
  { id: 'plumber-mag', domain: 'plumbermag.com', siteName: 'Plumber Magazine', relevantUrl: 'https://www.plumbermag.com', opportunityType: 'journalist', grade: 'B', campaignSegment: 'E', relevanceScore: 7, priority: 'medium', recommendedAngle: 'Plumbing trade publication — water hardness and plumbing risk data story for plumbing professionals. Covers residential and commercial plumbing', targetAsset: '/research/us-water-hardness-plumbing-risk', outreachStatus: 'pending', lastContactDate: '', followUpDate: '', notes: 'New prospect replacing plumbing-today (which was a local plumbing company, not a trade pub). Real trade publication with plumbing industry coverage.' },
];

// ── Classification Summary ────────────────────────────────────────
// Original 50 prospects reviewed:
//   A (Verified High-Value): 10
//   B (Verified Medium-Value): 24
//   C (Removed): 13
//   D (Needs Research): 1
// New prospects added: 5 (boston-globe, san-diego-tribune, tapwaterdata, hardwaterhq, plumber-mag, purewaterblog)
// Total verified prospects: 46
//
// Campaign distribution:
//   A (Data Story): 5 prospects
//   B (Local City): 9 prospects
//   C (Resource Update): 14 prospects
//   D (Embeddable Tool): 1 prospect (needs specific site identification)
//   E (Expert/Reference): 7 prospects
//
// Removed prospects and reasons:
//   epa-sdwis, cdc-water, energystar — government sites, will not link externally
//   nrdc-water — environmental org, tangential relevance
//   iapmo — code organization, unlikely to link
//   pmm-magazine — UK plumbing magazine, irrelevant for US city data
//   zillow, redfin — real estate platforms, no editorial water quality content
//   water-env-federation — professional org, low consumer relevance
//   home-improvement-directory — low-quality directory
//   hgtv — broad lifestyle, no specific water quality content
//   apartment-therapy — broad lifestyle, low relevance
//   plumbing-today — verified as local plumbing company in Poughkeepsie NY, NOT a trade publication
//   city-water-utilities — too vague, needs specific site identification
