export const STATE_INTROS = {
  'new-york': `New York's plumbing landscape is shaped by one of the oldest and most densely built urban environments in the United States. From the five boroughs of New York City to the older industrial cities upstate, plumbers here work on systems that span more than a century of construction. State plumbing work is regulated by the New York State Department of State, Division of Building Standards and Codes, while New York City maintains its own plumbing code through the Department of Buildings. Licensed master plumbers must meet experience and examination requirements before performing work in the state.

The climate drives much of the emergency demand. Upstate New York and the Hudson Valley experience long winters with temperatures well below freezing, while even New York City sees sustained cold snaps that freeze pipes in uninsulated exterior walls, crawl spaces, and attics. The most common winter emergencies are frozen pipes, burst water lines, and boiler failures. In summer, combined sewer systems in New York City can overflow during heavy rainfall, leading to basement backups and drain flooding.

Across the state, aging infrastructure is a constant factor. Pre-war buildings in NYC, Buffalo, Rochester, and Albany still rely on cast iron drain stacks, galvanized steel supplies, and in some cases original lead service lines. Water is supplied by large municipal systems such as the New York City Department of Environmental Protection and various regional authorities. Homeowners should test their main shutoff valve annually, insulate any exposed pipes before winter, and schedule water heater flushing if they live in areas with hard water.`,

  'california': `California's plumbing systems must handle a wide range of climates, soils, and water qualities across the state. From coastal cities with mild temperatures to inland deserts with extreme heat, the plumbing challenges differ dramatically by region. The state licenses plumbers through the Contractors State License Board, which requires a trade exam, experience, and bonding. Many cities and counties also enforce local water conservation and plumbing fixture standards.

Earthquakes and expansive clay soils place unique stress on underground pipes. In the Los Angeles Basin and the Bay Area, slab leaks are common because soil movement shifts the foundation and shears copper supply lines. In inland areas such as the Central Valley and the Inland Empire, hard water with high mineral content shortens water heater life and narrows pipe openings over time. Drought cycles also affect water pressure and supply stability, which can stress older plumbing systems.

The state's water supply is a mix of local groundwater, Sierra Nevada snowmelt, and Colorado River imports. Utilities such as the Los Angeles Department of Water and Power and the San Francisco Public Utilities Commission manage large systems. Common emergencies include slab leaks, water heater failures, sewer line root intrusion, and backflow issues. Homeowners should monitor water pressure, flush water heaters annually in hard-water areas, and know how to shut off water at the main valve before an earthquake or major leak.`,

  'texas': `Texas combines rapid population growth, wide temperature swings, and diverse soil conditions, all of which affect plumbing reliability. The Texas State Board of Plumbing Examiners oversees licensing, and plumbers must meet state experience and testing requirements. Many municipalities, including Houston, Dallas, San Antonio, and Austin, add local code amendments and permit rules.

The climate is one of the biggest risk factors. North Texas and the Panhandle experience hard freezes that burst pipes in uninsulated attics and exterior walls. Central Texas sees sudden ice storms and rapid thaw cycles. South Texas and the Gulf Coast face hurricanes, flooding, and high humidity that corrode metal fixtures and accelerate mold growth after leaks. Expansive clay soils across the state shift foundations seasonally, which stresses slab plumbing and underground sewer lines.

Water systems vary by region. East Texas has softer water, while West Texas and the Hill Country often have very hard water with high mineral content. Major utilities include Houston Public Works, Dallas Water Utilities, and the San Antonio Water System. Common emergencies include burst pipes during freezes, slab leaks from soil movement, water heater failures, and sewer backups from storm flooding. Preventive steps include pipe insulation before winter, foundation watering during drought, and regular water heater maintenance.`,

  'florida': `Florida's plumbing environment is defined by heat, humidity, high water tables, and coastal exposure. The state licenses plumbers through the Department of Business and Professional Regulation, and local counties often require additional permits for water heater replacements, sewer connections, and backflow prevention. Because much of the state is at or near sea level, drainage and sewer system design are critical.

The climate creates year-round plumbing demand. High humidity accelerates corrosion of metal pipes and fixtures, while hard water in many aquifers deposits calcium scale inside water heaters and supply lines. Hurricanes and tropical storms cause flooding, sewer system overload, and contamination risks. The high water table means that basements are rare, but slab leaks and foundation drainage issues are common, especially in areas with limestone geology.

Florida's water comes from the Floridan Aquifer, surface water, and desalination in some coastal areas. Utilities such as Miami-Dade Water and Sewer, Orlando Utilities Commission, and Tampa Bay Water serve large populations. Common emergencies include water heater failures, sewer backups after heavy rain, slab leaks, and clogged drains from tree roots. Homeowners should flush water heaters regularly, install hurricane-rated fixtures where required, and keep gutters and drains clear to reduce flooding risk.`,

  'illinois': `Illinois sits at the intersection of cold Midwest winters and aging industrial-era infrastructure. The Illinois Department of Public Health licenses plumbers, and the city of Chicago maintains its own plumbing code and licensing system. Many homes in Chicago, Peoria, Rockford, and Springfield were built before modern plumbing standards, which means original cast iron, galvanized steel, and even lead service lines are still in use.

Winters are the dominant emergency driver. Lake-effect snow and sustained subzero temperatures freeze pipes in crawl spaces, garages, and exterior walls across the state. The freeze-thaw cycle also opens small cracks in aging water mains, causing street leaks and pressure drops. Spring brings rapid thaws that can overwhelm sewer systems and sump pumps, particularly in homes with older drain tile.

Water supply is managed by city and regional authorities, including the Chicago Department of Water Management. Common plumbing emergencies include frozen and burst pipes, water heater failures, sewer backups, and clogged drains from grease and debris. Homeowners should insulate pipes before winter, test the main shutoff valve annually, and consider a sump pump inspection in spring to prepare for heavy rains.`,

  'pennsylvania': `Pennsylvania's plumbing systems reflect the state's industrial history and varied geography. From the row homes of Philadelphia and Pittsburgh to the older rural homes in the central counties, plumbers work on a wide range of materials and eras. The state licenses plumbers through the Department of Labor and Industry, and cities such as Philadelphia and Pittsburgh have their own plumbing inspection and permitting offices.

The climate produces cold winters and wet springs. Freeze-thaw cycles in winter are a leading cause of burst pipes, especially in homes with uninsulated basements and crawl spaces. Older cities have combined sewer systems that can overflow during heavy rain, causing basement backups. The hilly terrain in the western part of the state also creates drainage challenges and foundation water issues.

Water systems include the Philadelphia Water Department, Pittsburgh Water and Sewer Authority, and many smaller municipal authorities. Common emergencies include frozen pipes, sewer backups, water main breaks, and water heater failures in older homes. Homeowners should know the location of their main shutoff, avoid pouring grease down drains, and insulate exposed pipes before winter.`,

  'arizona': `Arizona's plumbing systems face extreme heat, hard water, and rapid suburban expansion. The Arizona Registrar of Contractors licenses plumbers, and many municipalities require permits for water heater replacements, repiping, and sewer connections. The dry climate and high mineral content of water sources put continuous stress on pipes, fixtures, and appliances.

Summer temperatures above 110°F in Phoenix and Tucson can cause CPVC and copper joints to expand and shift, leading to leaks. Hard water is widespread, with high calcium and magnesium levels that scale water heaters, faucets, and dishwashers. In higher elevations such as Flagstaff and Prescott, freezing winter nights create a different set of risks for exposed pipes and outdoor fixtures.

Water is drawn from the Colorado River, groundwater, and reclaimed sources. Major providers include the Salt River Project, Phoenix Water Services, and Tucson Water. Common emergencies include water heater failures, slab leaks, hard-water scale blockages, and burst pipes during rare freeze events. Homeowners should install water softeners if needed, flush water heaters annually, and insulate outdoor hose bibs and exposed pipes in higher elevations.`,

  'ohio': `Ohio's plumbing environment combines lake-effect winters, aging cities, and industrial legacy infrastructure. The Ohio Department of Commerce licenses plumbers through its Construction Industry Licensing Board, and major cities such as Cleveland, Columbus, and Cincinnati enforce local plumbing codes and inspections. Many neighborhoods in these cities were built before 1960 and still have original galvanized or cast iron plumbing.

Lake-effect snow and subzero temperatures in winter are a major cause of frozen and burst pipes, especially in homes with unheated basements or crawl spaces. Spring thaws and heavy rains can overwhelm older sewer systems and cause basement flooding. The clay-heavy soils in much of the state also contribute to foundation movement and slab stress.

Water is provided by city utilities such as Cleveland Water, Columbus Public Utilities, and Greater Cincinnati Water Works. Common emergencies include burst pipes, water heater failures, sewer backups, and clogged drains from tree roots. Homeowners should insulate pipes before winter, test sump pumps in spring, and avoid flushing wipes or other non-biodegradable items.`,

  'north-carolina': `North Carolina's fast-growing cities and varied geography create a mix of plumbing challenges. The State Board of Examiners of Plumbing, Heating, and Fire Sprinkler Contractors licenses plumbers, and local counties issue permits for most major work. Coastal areas face salt air and hurricane flooding, while the Piedmont and Mountain regions deal with hard water and freeze risk.

Rapid population growth has strained municipal water and sewer infrastructure in Raleigh, Charlotte, Durham, and Greensboro. Newer subdivisions often have modern PVC systems, but older neighborhoods still have cast iron and galvanized lines. The state's red clay soil expands and contracts with moisture, stressing slab plumbing and foundations. In the mountains, freezing temperatures create winter pipe risks.

Water utilities include Charlotte Water, Raleigh Water, and numerous regional authorities. Common emergencies include water heater failures, slab leaks, sewer backups after heavy rain, and frozen pipes in higher elevations. Homeowners should maintain water heaters, clear outdoor drains, and insulate exposed pipes in winter, especially in homes above 2,000 feet elevation.`,

  'indiana': `Indiana's plumbing systems are shaped by cold winters, hard water, and a mix of urban and rural housing. The Indiana Professional Licensing Agency oversees plumbing licenses, and cities such as Indianapolis, Fort Wayne, and Evansville have local plumbing inspectors. Much of the housing stock in the state was built between 1950 and 1990, with a mix of copper, galvanized, and PVC materials.

Winters are cold enough to freeze pipes in uninsulated spaces, and water heater failures spike during the coldest months. Hard water is common across the state, particularly in areas that draw from limestone aquifers. This mineral content shortens the life of water heaters and reduces flow in faucets and showerheads over time. Spring storms can also overwhelm older sewer systems and cause backups.

Water providers include Citizens Energy Group in Indianapolis and various municipal utilities. Common emergencies include frozen pipes, water heater failures, clogged drains, and sewer backups. Homeowners should flush water heaters annually, insulate pipes in crawl spaces and garages, and test the main shutoff valve each year.`,

  'washington': `Washington's plumbing environment is dominated by heavy rainfall, mild coastal temperatures, and mountainous terrain. The Washington State Department of Labor and Industries licenses plumbers, and cities such as Seattle, Spokane, and Tacoma have local plumbing codes and inspection requirements. The state's wet climate means drainage, waterproofing, and sump pump reliability are critical.

Western Washington receives heavy rain for much of the year, which keeps groundwater levels high and places constant demand on perimeter drains and sump pumps. Older homes in Seattle and Tacoma may still have original galvanized or cast iron plumbing. In eastern Washington and the Cascade foothills, freezing winter nights can burst pipes in uninsulated spaces. The mountainous regions also face snow load and freeze-thaw issues.

Water is provided by Seattle Public Utilities, Spokane City Water, and many smaller municipal systems. Common emergencies include sump pump failures, sewer backups, water heater failures, and frozen pipes. Homeowners should test sump pumps before the rainy season, maintain water heaters, and ensure outdoor hose bibs are drained before winter.`,

  'colorado': `Colorado's plumbing systems must handle high altitude, cold nights, and wide daily temperature swings. The Colorado Department of Regulatory Agencies licenses plumbers, and municipalities such as Denver, Colorado Springs, and Boulder have their own plumbing inspectors and permit requirements. The state's elevation affects water pressure, water heater performance, and pipe expansion.

Front Range cities experience rapid weather changes, with warm afternoons followed by freezing nights in spring and fall. This stresses exposed pipes and outdoor fixtures. In the mountains, winter temperatures drop well below zero, making pipe insulation essential. Hard water is common in areas that draw from mineral-rich aquifers and mountain runoff, which shortens water heater life and leaves scale deposits.

Water providers include Denver Water, Colorado Springs Utilities, and numerous regional districts. Common emergencies include frozen pipes, water heater failures, burst outdoor hose bibs, and leaks from pressure changes. Homeowners should insulate all exposed pipes, drain hose bibs before winter, and consider a water softener if hard water is present.`,

  'tennessee': `Tennessee's plumbing environment combines humid summers, surprise cold snaps, and a mix of old and new housing. The Tennessee Board for Licensing Contractors regulates plumbers, and larger cities such as Nashville, Memphis, and Knoxville require permits for water heater replacements, repiping, and major repairs. Many historic homes in these cities still have galvanized or cast iron plumbing.

Although winters are generally mild, Arctic air outbreaks can drop temperatures below freezing for several days, catching homeowners off guard and freezing pipes in uninsulated crawl spaces. Summer humidity accelerates corrosion and mold growth after leaks. The state's clay soils shift with moisture, stressing slab plumbing and sewer lines. In Memphis, the high water table adds drainage challenges.

Water systems include Memphis Light, Gas and Water, Nashville Metro Water Services, and Knoxville Utilities Board. Common emergencies include frozen pipes, water heater failures, slab leaks, and sewer backups. Homeowners should insulate exposed pipes, flush water heaters, and keep gutters and drains clear to reduce foundation water pressure.`,

  'georgia': `Georgia's plumbing systems face red clay soils, humid summers, and occasional hard freezes. The Georgia State Construction Industry Licensing Board licenses plumbers, and cities such as Atlanta, Augusta, and Savannah enforce local plumbing codes. Much of the state's housing growth is in suburban Atlanta, where newer homes have modern PVC systems, but older neighborhoods still have cast iron and galvanized plumbing.

Expansive red clay soil expands when wet and shrinks during drought, shifting foundations and stressing slab plumbing and sewer lines. This is one of the leading causes of slab leaks in the Atlanta metro area. Humid summers encourage mold growth after leaks and can corrode metal fixtures. While winters are mild, hard freezes do occur and can burst uninsulated outdoor pipes and hose bibs.

Water providers include Atlanta Department of Watershed Management, Augusta Utilities, and Savannah Water. Common emergencies include slab leaks, water heater failures, clogged drains, and frozen pipes during cold snaps. Homeowners should maintain consistent soil moisture around foundations, insulate outdoor fixtures, and flush water heaters annually.`,

  'michigan': `Michigan's plumbing environment is defined by Great Lakes winters, aging infrastructure, and varied housing stock. The Michigan Department of Licensing and Regulatory Affairs licenses plumbers, and cities such as Detroit, Grand Rapids, and Ann Arbor have local inspectors. Many homes in the state were built before 1970 and still have galvanized steel or cast iron plumbing.

Winter is the dominant emergency driver. Lake-effect snow and prolonged subzero temperatures freeze pipes in basements, crawl spaces, and exterior walls. The freeze-thaw cycle also opens cracks in water mains and service lines. Spring thaws can overwhelm sewers and sump pumps, especially in homes with older drain tile. Water hardness varies by region, with some areas drawing from limestone aquifers.

Water providers include Detroit Water and Sewerage Department, Grand Rapids Water System, and many municipal utilities. Common emergencies include frozen and burst pipes, water heater failures, sewer backups, and sump pump failures. Homeowners should insulate pipes before winter, test the main shutoff valve, and inspect sump pumps each spring.`,

  'virginia': `Virginia's plumbing systems span coastal plains, Piedmont hills, and mountain valleys, each with different risks. The Virginia Department of Professional and Occupational Regulation licenses plumbers, and cities such as Richmond, Virginia Beach, and Norfolk have local plumbing inspectors. Historic homes in Richmond, Alexandria, and Charlottesville often contain original cast iron, galvanized, or even lead plumbing components.

Coastal areas face hurricane flooding, salt air corrosion, and high water tables. The Piedmont region deals with clay soils that shift with moisture and stress slab plumbing. Western Virginia and the mountains experience freezing winters that burst pipes in uninsulated spaces. Hard water is present in many areas, shortening water heater life and leaving scale deposits.

Water providers include the City of Richmond Department of Public Utilities, Virginia Beach Public Utilities, and numerous regional authorities. Common emergencies include frozen pipes, water heater failures, slab leaks, and sewer backups. Homeowners should flush water heaters, insulate pipes in winter, and ensure outdoor drainage is clear before storms.`,

  'maryland': `Maryland's plumbing environment is shaped by dense urban housing, coastal flooding, and aging infrastructure. The Maryland Board of Plumbing licenses plumbers, and Baltimore and the Washington suburbs have their own permitting and inspection processes. Many rowhomes in Baltimore and older suburbs still have original cast iron drains and galvanized supply lines.

The state's location on the Chesapeake Bay means coastal flooding and storm surge are recurring concerns, especially in low-lying areas. Heavy rains can overwhelm combined sewer systems in Baltimore, causing basement backups. Winters are cold enough to freeze pipes in uninsulated basements and crawl spaces, particularly in older homes with poor insulation. Hard water is common in areas that draw from limestone aquifers.

Water providers include Baltimore City Department of Public Works, Washington Suburban Sanitary Commission, and Anne Arundel County. Common emergencies include sewer backups, frozen pipes, water heater failures, and leaks from aging pipe materials. Homeowners should test the main shutoff valve, avoid pouring grease down drains, and maintain sump pumps.`,

  'wisconsin': `Wisconsin's plumbing systems face some of the harshest winter conditions in the continental United States. The Wisconsin Department of Safety and Professional Services licenses plumbers, and cities such as Milwaukee, Madison, and Green Bay have local inspectors. Many homes in the state were built before 1980 and have original galvanized steel or copper plumbing that is vulnerable to freezing.

Winter is the leading cause of plumbing emergencies. Extended periods of subzero temperatures freeze pipes in basements, crawl spaces, garages, and exterior walls. The spring thaw can then cause burst pipes as pressure returns. Water hardness is high in much of the state, which shortens water heater life and leaves scale in fixtures. Summer storms can also overwhelm sewer systems and sump pumps.

Water providers include Milwaukee Water Works, Madison Water Utility, and Green Bay Water Utility. Common emergencies include frozen and burst pipes, water heater failures, sewer backups, and clogged drains. Homeowners should insulate all exposed pipes, drain hose bibs, flush water heaters, and test sump pumps before spring.`,

  'oregon': `Oregon's plumbing environment is shaped by heavy rainfall, mild temperatures, and mountainous terrain. The Oregon Building Codes Division licenses plumbers, and cities such as Portland, Eugene, and Salem have local plumbing inspectors and permit requirements. The western part of the state receives consistent rain for much of the year, which keeps groundwater high and tests drainage systems constantly.

Portland and Eugene have many older homes with original cast iron and galvanized plumbing. The Willamette Valley experiences occasional freezing nights that can burst outdoor pipes and hose bibs. In central and eastern Oregon, winters are colder and harder water is more common, increasing water heater scale and freeze risk. Earthquake risk in the western part of the state also places stress on rigid pipe systems.

Water providers include Portland Water Bureau, Eugene Water and Electric Board, and Salem Public Works. Common emergencies include sump pump failures, sewer backups, water heater failures, and frozen pipes. Homeowners should test sump pumps before the rainy season, flush water heaters, and secure water heaters and piping against seismic movement.`,

  'nevada': `Nevada's plumbing environment is defined by desert heat, extreme hard water, and rapid growth. The Nevada State Contractors Board licenses plumbers, and Las Vegas, Reno, and Henderson have local building departments and permit requirements. The dry climate and high mineral content of water sources create some of the hardest water conditions in the country.

Summer temperatures in Las Vegas and southern Nevada regularly exceed 105°F, which expands pipes and stresses water heaters. Hard water deposits calcium scale rapidly inside water heaters, faucets, and dishwashers, shortening appliance life. In northern Nevada, Reno and Carson City experience freezing winter nights that can burst uninsulated outdoor pipes and hose bibs.

Water providers include the Las Vegas Valley Water District, Reno Water, and Carson City Public Works. Common emergencies include water heater failures, hard-water scale blockages, slab leaks, and frozen pipes in northern areas. Homeowners should flush water heaters at least annually, consider water softeners, and insulate outdoor fixtures before winter.`,

  'oklahoma': `Oklahoma's plumbing systems face ice storms, tornadoes, expansive clay soils, and hard water. The Oklahoma Construction Industries Board licenses plumbers, and cities such as Oklahoma City, Tulsa, and Norman have local plumbing inspectors. The state's weather is highly variable, with freezing winters and hot, stormy summers.

Ice storms are a major cause of winter pipe bursts in Oklahoma, particularly when power outages leave homes without heat. Expansive clay soils shift with moisture, causing foundation movement and slab leaks. Tornadoes and severe storms can damage outdoor plumbing and cause water contamination. Hard water is common in many areas, leading to scale buildup in water heaters and fixtures.

Water providers include Oklahoma City Utilities, Tulsa Water, and numerous municipal systems. Common emergencies include burst pipes from ice storms, water heater failures, slab leaks, and storm-related sewer backups. Homeowners should insulate pipes, maintain a backup heat source during winter storms, and flush water heaters regularly.`,

  'new-mexico': `New Mexico's plumbing environment combines high-altitude cold nights, desert heat, and very hard water. The New Mexico Regulation and Licensing Department licenses plumbers, and Albuquerque, Santa Fe, and Las Cruces have local building codes and inspectors. The state's elevation means water boils at lower temperatures and water heaters work harder than at sea level.

Desert heat in summer expands pipes and stresses joints, while high-altitude locations such as Santa Fe and Taos experience freezing nights year-round. Hard water is widespread, with high mineral content that leaves scale in water heaters, pipes, and appliances. Many homes in the state rely on wells or small municipal systems that may have variable pressure.

Water providers include Albuquerque Water Utility Authority, Santa Fe Water, and Las Cruces Utilities. Common emergencies include water heater failures, hard-water scale blockages, frozen pipes, and leaks from pressure changes. Homeowners should flush water heaters frequently, insulate exposed pipes, and monitor water pressure.`,

  'missouri': `Missouri's plumbing systems face wide seasonal temperature swings, clay soils, and aging infrastructure. The Missouri Division of Professional Registration licenses plumbers, and St. Louis, Kansas City, and Springfield have local plumbing inspectors and codes. Much of the housing in St. Louis and Kansas City was built before 1960 and still contains galvanized or cast iron plumbing.

Winters can bring extended freezes that burst pipes in uninsulated basements and crawl spaces. Summers are hot and humid, which accelerates corrosion and mold growth after leaks. The state's clay soils expand and contract with moisture, shifting foundations and stressing slab plumbing. Storms and flash flooding can overwhelm sewers and cause backups.

Water providers include Missouri American Water, Kansas City Water Services, and St. Louis City Water. Common emergencies include frozen pipes, water heater failures, sewer backups, and slab leaks. Homeowners should insulate pipes before winter, test sump pumps, and flush water heaters annually.`,

  'nebraska': `Nebraska's plumbing environment is shaped by harsh winters, hard water, and a mix of urban and rural housing. The Nebraska Department of Labor licenses plumbers, and Omaha, Lincoln, and Grand Island have local inspectors and permit requirements. The state experiences some of the coldest winter temperatures in the Midwest, making frozen pipe emergencies a recurring problem.

Polar vortex events can drop temperatures below zero for extended periods, freezing pipes in basements, crawl spaces, and garages. The freeze-thaw cycle in spring then causes burst pipes. Hard water is common in areas that draw from limestone aquifers, leaving scale in water heaters and reducing fixture flow. Rural homes may rely on wells and septic systems, which have their own maintenance needs.

Water providers include Metropolitan Utilities District in Omaha, Lincoln Water System, and numerous municipal utilities. Common emergencies include frozen and burst pipes, water heater failures, well pump problems, and sewer backups. Homeowners should insulate exposed pipes, drain hose bibs, and maintain water heaters and sump pumps.`,

  'louisiana': `Louisiana's plumbing environment is defined by low elevation, high humidity, coastal flooding, and aging infrastructure. The Louisiana State Plumbing Board licenses plumbers, and New Orleans, Baton Rouge, and Shreveport have local plumbing inspectors and codes. Much of the state's population lives at or below sea level, which makes drainage and sewer systems critical.

Hurricanes and tropical storms cause flooding, sewer system overload, and contamination risks. High humidity accelerates corrosion of metal pipes and fixtures. The soil in southern Louisiana is soft and unstable, which can shift foundations and stress underground plumbing. Winters are generally mild, but occasional freezes can burst uninsulated outdoor pipes.

Water providers include New Orleans Sewerage and Water Board, Baton Rouge Water Company, and Shreveport Water. Common emergencies include sewer backups, water heater failures, slab leaks, and flooding-related plumbing damage. Homeowners should maintain sump pumps, clear drains, and secure outdoor fixtures before storms.`,

  'minnesota': `Minnesota's plumbing environment is dominated by extreme cold, hard water, and aging infrastructure. The Minnesota Department of Labor and Industry licenses plumbers, and Minneapolis, St. Paul, and Rochester have local plumbing inspectors and permit requirements. The state has some of the harshest winter conditions in the country, making frozen pipe emergencies a near-annual event.

Temperatures regularly drop well below zero for extended periods, freezing pipes in basements, crawl spaces, garages, and exterior walls. The spring thaw then causes burst pipes and water main breaks. Hard water is common in many areas, shortening water heater life and leaving scale in fixtures. Many homes in the Twin Cities were built before 1960 and have older plumbing materials.

Water providers include Minneapolis Water Works, St. Paul Regional Water Services, and Rochester Public Utilities. Common emergencies include frozen and burst pipes, water heater failures, water main breaks, and sewer backups. Homeowners should insulate all exposed pipes, drain hose bibs, flush water heaters, and maintain sump pumps.`,

  'kentucky': `Kentucky's plumbing environment combines humid summers, cold winters, and aging housing stock. The Kentucky Department of Housing, Buildings and Construction licenses plumbers, and Louisville, Lexington, and Bowling Green have local inspectors and codes. Many homes in the state's historic neighborhoods still have original galvanized steel or cast iron plumbing.

Ohio River valley humidity accelerates corrosion of metal pipes and fixtures. Winter cold snaps freeze pipes in uninsulated basements and crawl spaces. The region's clay soils shift with moisture, stressing foundations and slab plumbing. Heavy spring rains can overwhelm older sewer systems and cause basement backups.

Water providers include Louisville Water Company, Kentucky American Water, and various municipal utilities. Common emergencies include frozen pipes, water heater failures, sewer backups, and leaks from aging pipe materials. Homeowners should insulate pipes, test sump pumps, and flush water heaters annually.`,

  'massachusetts': `Massachusetts combines some of the oldest housing stock in the nation with harsh New England winters, creating persistent plumbing demand. The Massachusetts Board of State Examiners of Plumbers and Gas Fitters licenses plumbers statewide, and Boston, Worcester, Springfield, and Cambridge enforce local plumbing codes. Many homes in these cities were built before 1900 and still contain lead service lines, galvanized steel, and cast iron drain stacks.

Winter is the dominant emergency driver. Temperatures regularly drop below 20°F across the state, and ground frost can penetrate 36 to 48 inches. Frozen pipes in uninsulated Victorian-era basements and exterior walls are the most frequent emergency call. The MWRA operates combined sewers in Boston's oldest neighborhoods, which can overflow during heavy rain and cause basement backups. Worcester and Springfield face similar combined sewer issues in their historic cores.

Water is supplied by the Massachusetts Water Resources Authority, Providence Water, and numerous municipal systems. Common emergencies include frozen and burst pipes, corroded galvanized supply lines, sewer backups, and water heater failures. Homeowners should insulate exposed pipes before winter, locate the main shutoff valve, and consider replacing lead service lines during renovations.`,

  'district-of-columbia': `Washington, DC's plumbing infrastructure reflects the city's age and density. The DC Board of Industrial Trades licenses plumbers, and DC Water enforces local plumbing and sewer codes. Many rowhouses in Capitol Hill, Georgetown, and Adams Morgan were built before 1950 and still have original lead service lines, cast iron drains, and galvanized supply pipes that are now failing.

The climate produces cold winters with sustained freezing temperatures and humid summers with heavy thunderstorms. Freeze-thaw cycles burst pipes in uninsulated basements and exterior walls, particularly in older brick rowhouses. DC Water's combined sewer system serves the entire district, and during heavy rain the system can overflow into the Anacostia and Potomac rivers, causing basement backups in low-lying neighborhoods.

Water is provided by DC Water, which draws from the Potomac River and treats it at the Blue Plains Advanced Wastewater Treatment Plant. Common emergencies include failing clay sewer laterals, lead and galvanized service line replacement, frozen pipes, and sewer backups. Homeowners should test the main shutoff valve annually, avoid pouring grease down drains, and insulate exposed pipes before winter.`,

  'alabama': `Alabama's plumbing systems face humid subtropical conditions, clay soils, and a mix of older and newer housing. The Alabama Plumbers and Gas Fitters Examination Board licenses plumbers, and cities such as Birmingham, Huntsville, Montgomery, and Mobile enforce local codes. Many homes built before 1970 still have galvanized steel supply lines and cast iron drains that are corroding from within.

While winters are generally mild, Arctic air outbreaks can drop temperatures below freezing for several days, catching homeowners off guard and freezing pipes in uninsulated crawl spaces. The state's piedmont clay soils expand when wet and shrink during drought, shifting foundations and stressing slab plumbing and sewer lines. In Mobile and along the Gulf Coast, salt air corrosion attacks copper lines and hurricanes cause storm-driven sewer backups.

Water providers include Birmingham Water Works, Huntsville Utilities, Montgomery Water Works, and the Mobile Area Water and Sewer System. Common emergencies include corroded galvanized steel pipes, tree root intrusion in clay sewer lines, storm-driven sewer backups, and frozen pipes during cold snaps. Homeowners should maintain consistent soil moisture around foundations, insulate exposed pipes, and schedule camera inspections of older sewer laterals.`,

  'arkansas': `Arkansas's plumbing environment combines humid summers, expansive clay soils, and a mix of urban and rural housing. The Arkansas Department of Health regulates plumbing through its Plumbing and Natural Gas Division, and Little Rock enforces local plumbing codes. Many homes in the state were built between 1950 and 1990 with copper supply lines and cast iron drains that are reaching the end of their service life.

Expansive clay soils across the state shift with moisture changes, stressing slab foundations and underground plumbing. This is a leading cause of slab leaks in the Little Rock metro area. Winter cold snaps can freeze pipes in uninsulated crawl spaces, though the risk is lower than in northern states. Summer humidity accelerates corrosion of metal pipes and fixtures, and heavy spring storms can overwhelm older sewer systems.

Water providers include Central Arkansas Water and various municipal utilities. Common emergencies include slab leaks from expansive clay, corroded galvanized steel in pre-1970 homes, tree root intrusion in sewer lines, and storm-driven sewer backups. Homeowners should maintain consistent soil moisture around foundations, flush water heaters annually, and keep gutters and drains clear.`,

  'hawaii': `Hawaii's plumbing environment is defined by salt air corrosion, volcanic geology, and tropical humidity. The Hawaii Board of Electricians and Plumbers licenses plumbers, and Honolulu and other counties enforce local plumbing codes. The state's isolation means that replacement parts and specialized fixtures may take longer to source, making preventive maintenance especially important.

Salt air from the Pacific accelerates corrosion of copper lines, galvanized fittings, and exposed metal pipes, particularly in coastal properties. Volcanic basalt and coral fill create rocky soil conditions that make excavation and pipe repair more difficult. The warm, humid climate also encourages mold growth after even small leaks. While freezing is not a concern, tropical storms and heavy rainfall can overwhelm drainage systems and cause sewer backups.

Water is provided by the Board of Water Supply in Honolulu and county water departments on the neighbor islands. Common emergencies include salt air corrosion on copper lines, deteriorated PVC in coastal properties, sewer backups after heavy rain, and water heater failures. Homeowners should schedule annual corrosion inspections, install dielectric unions where dissimilar metals meet, and keep gutters and drainage clear before storm season.`,

  'idaho': `Idaho's plumbing systems must handle high-altitude freeze-thaw cycles, hard water, and rocky soil conditions. The Idaho Division of Building Safety licenses plumbers, and Boise, Nampa, Idaho Falls, and Pocatello enforce local plumbing codes. The state's mix of older homes with copper pipes and newer construction with PEX creates a varied plumbing landscape.

Winter temperatures regularly drop below freezing across the state, and in higher-elevation cities like Idaho Falls and Pocatello, temperatures can fall below zero. Frozen pipes in uninsulated crawl spaces, garages, and exterior walls are the most common winter emergency. Hard water is widespread, with mineral content from rocky aquifers that scales water heaters, faucets, and supply lines. The rocky, alluvial soil makes excavation difficult and expensive, increasing repair costs.

Water providers include Suez Water Idaho, Idaho Falls Water Department, and various municipal systems. Common emergencies include frozen pipes, hard water scale blockages, water heater failures, and leaks from pipe joint expansion. Homeowners should insulate all exposed pipes, drain hose bibs before winter, flush water heaters annually, and consider a water softener if hardness exceeds 150 ppm.`,

  'iowa': `Iowa's plumbing environment is shaped by extreme seasonal temperature swings, hard water, and glacial soil conditions. The Iowa Plumbing and Mechanical Systems Board licenses plumbers, and Des Moines, Cedar Rapids, and other cities enforce local codes. Many homes in the state were built between 1950 and 1990 with copper supply lines and cast iron drains.

Winter is the dominant emergency driver. Temperatures in Des Moines and Cedar Rapids regularly drop below zero during polar vortex events, freezing pipes in basements, crawl spaces, and exterior walls. The freeze-thaw cycle in spring then causes burst pipes as pressure returns. Hard water is among the worst in the nation, with Cedar Rapids recording 285 ppm — among the highest of any major US city. This mineral content rapidly scales water heaters and narrows pipe openings.

Water providers include Des Moines Water Works, Cedar Rapids Water Department, and numerous municipal utilities. Common emergencies include frozen and burst pipes, hard water scale blockages, water heater failures, and sewer backups. Homeowners should insulate all exposed pipes, install a water softener if hardness exceeds 120 ppm, and flush water heaters at least annually.`,

  'kansas': `Kansas's plumbing systems face expansive clay soils, hard water, and severe weather extremes. The state does not require a statewide plumbing license, leaving licensing to individual municipalities. Wichita, Overland Park, and Kansas City enforce their own plumbing codes and permit requirements. Many homes in the state were built between 1960 and 1990 with copper and PVC systems.

Expansive clay soils across the state shift with moisture changes, stressing slab foundations and underground plumbing. This is a leading cause of slab leaks in the Wichita area. Hard water is severe, with Wichita recording 245 ppm — among the hardest water of any major US city. Winter ice storms can burst pipes in uninsulated areas, particularly when power outages leave homes without heat. Summer thunderstorms can overwhelm sewer systems and cause backups.

Water providers include the City of Wichita Water, WaterOne in Johnson County, and various municipal utilities. Common emergencies include hard water scale blockages, slab leaks from expansive clay, frozen pipes during ice storms, and storm-driven sewer backups. Homeowners should install a water softener, maintain consistent soil moisture around foundations, and insulate exposed pipes before winter.`,

  'rhode-island': `Rhode Island's plumbing systems reflect the state's industrial history and coastal location. The Rhode Island Department of Labor and Training licenses plumbers through its Plumbers and Irrigation Specialists Board, and Providence and other cities enforce local plumbing codes. Many homes in Providence, Warwick, and Cranston were built before 1950 and still have lead service lines, galvanized steel, and cast iron plumbing.

Coastal salt air accelerates corrosion of metal pipes and fixtures, particularly in homes near Narragansett Bay. Winter temperatures regularly drop below freezing, and freeze-thaw cycles burst pipes in uninsulated basements and crawl spaces. The Narragansett Bay Commission operates combined sewers in the oldest neighborhoods of Providence, which can overflow during heavy rain and cause basement backups.

Water is provided by Providence Water, which draws from the Scituate Reservoir, and various municipal systems. Common emergencies include corroded galvanized supply lines in pre-1950 homes, frozen pipes, sewer backups from combined sewer overflows, and water heater failures. Homeowners should insulate exposed pipes, test the main shutoff valve, and consider replacing lead service lines.`,

  'utah': `Utah's plumbing environment is defined by high altitude, extreme temperature swings, and very hard water. The Utah Division of Occupational and Professional Licensing (DOPL) licenses plumbers, and Salt Lake City, Provo, and Ogden enforce local plumbing codes. The state's rapid population growth has created a mix of older homes with galvanized and copper pipes and newer construction with PEX.

Winter temperatures in Salt Lake City regularly drop below freezing, and temperature swings of 30 to 40 degrees within a single day stress pipe joints and outdoor fixtures. Hard water is among the most severe in the nation, with Salt Lake City recording 225 ppm. This mineral content scales water heaters rapidly, narrows pipe openings, and shortens appliance life. The rocky, alluvial soil makes excavation difficult and increases repair costs.

Water providers include the Salt Lake City Department of Public Utilities and various municipal systems. Common emergencies include hard water scale blockages, frozen pipes in uninsulated areas, water heater failures, and leaks from pipe joint expansion. Homeowners should install a water softener, flush water heaters at least annually, and insulate all exposed pipes before winter.`,

  'alaska': `Alaska's plumbing systems face the most extreme cold conditions in the United States. The Alaska Department of Labor and Workforce Development licenses plumbers, and Anchorage, Fairbanks, and Juneau enforce local plumbing codes. The state's unique conditions — permafrost, extreme cold, and remote locations — create plumbing challenges found nowhere else in the country.

Winter temperatures in Anchorage regularly drop below zero, and in interior cities like Fairbanks, temperatures can reach minus 40°F. Frozen pipes in uninsulated areas are the dominant emergency, and the freeze season lasts from October through April. Permafrost in northern regions requires specialized pipe installation techniques, including insulated above-ground utility lines. Road salt used in urban areas accelerates corrosion of exposed metal pipes and fittings.

Water is provided by Anchorage Water and Wastewater Utility and various municipal systems. Common emergencies include frozen pipes, corrosion from road salt, water heater failures in hard-water areas, and sewer line freeze-ups. Homeowners should insulate all exposed pipes with heat tape or foam, keep a backup heat source during winter storms, and schedule annual inspections of water heater anode rods.`,

  'connecticut': `Connecticut's plumbing systems reflect the state's colonial history and coastal geography. The Connecticut Department of Consumer Protection licenses plumbers, and Bridgeport, New Haven, Hartford, and Stamford enforce local plumbing codes. Many homes in these cities were built before 1950 and still contain cast iron drains, galvanized supply lines, and in some cases lead service lines.

Winter is the dominant emergency driver. Temperatures regularly drop below freezing from December through March, and freeze-thaw cycles burst pipes in uninsulated basements and crawl spaces. Coastal areas face salt air corrosion that attacks copper lines and galvanized fittings. Combined sewer systems in Bridgeport, New Haven, and Hartford can overflow during heavy rain, causing basement backups in older neighborhoods.

Water providers include Aquarion Water Company, the South Central Connecticut Regional Water Authority, and the Metropolitan District Commission in Hartford. Common emergencies include corroded cast iron drain lines, frozen pipes, sewer backups from combined sewer overflows, and water heater failures. Homeowners should insulate exposed pipes, test sump pumps, and schedule camera inspections of older sewer laterals.`,

  'new-jersey': `New Jersey's plumbing environment is shaped by high-density urban infrastructure, coastal exposure, and aging housing stock. The New Jersey State Board of Examiners of Master Plumbers licenses plumbers, and Newark, Jersey City, and Trenton enforce local plumbing codes. Many homes in Newark and Jersey City were built before 1950 and still have lead service lines, cast iron drains, and galvanized supply pipes.

Winter temperatures regularly drop below freezing, and freeze-thaw cycles burst pipes in uninsulated brick rowhouses and older homes. The Passaic Valley Sewerage Commission operates a combined sewer system that can overflow during heavy rain, causing basement backups in Newark and surrounding areas. Coastal areas face salt air corrosion from the Atlantic, which attacks copper lines and metal fixtures in homes near the shore.

Water providers include Newark Water Department, Suez Water, and numerous municipal utilities. Common emergencies include lead service line replacement, frozen pipes in uninsulated rowhouses, corroded cast iron in pre-1940 homes, and sewer backups. Homeowners should locate the main shutoff valve, insulate exposed pipes, and consider replacing lead service lines during renovations.`,

  'south-dakota': `South Dakota's plumbing systems face extreme continental winters, hard water, and glacial soil conditions. The South Dakota Plumbing Commission licenses plumbers, and Sioux Falls, Rapid City, and Pierre enforce local plumbing codes. Many homes in the state were built between 1960 and 1990 with copper supply lines and PVC drains.

Winter is the dominant emergency driver. Temperatures in Sioux Falls regularly drop below zero during polar vortex events, and the freeze season extends from November through April. Frozen pipes in uninsulated basements, crawl spaces, and garages are the most common emergency. Hard water is severe, with Sioux Falls recording 195 ppm, which scales water heaters rapidly and narrows pipe openings over time. Glacial till and loam soils can shift with freeze-thaw cycles, stressing underground plumbing.

Water providers include the City of Sioux Falls Water Department and various municipal utilities. Common emergencies include frozen and burst pipes, hard water scale blockages, water heater failures, and sewer backups. Homeowners should insulate all exposed pipes, drain hose bibs before winter, install a water softener, and flush water heaters annually.`,

  'delaware': `Delaware's plumbing environment reflects its mid-Atlantic location, with seasonal freeze-thaw cycles and aging infrastructure in older neighborhoods. The Delaware Board of Plumbing, Heating, Ventilation, Air Conditioning and Refrigeration Examiners licenses plumbers, and Wilmington, Dover, and Newark enforce local plumbing codes. Many homes in Wilmington were built before 1960 and still have cast iron drains and galvanized supply lines.

Winters are cold enough to freeze pipes in uninsulated basements and crawl spaces, particularly in older homes with poor insulation. The freeze-thaw cycle also stresses older water mains and service lines. Wilmington's combined sewer system can overflow during heavy rain, causing basement backups in low-lying neighborhoods. Coastal areas near Lewes and Rehoboth face salt air corrosion and high water tables that stress underground plumbing.

Water providers include the City of Wilmington Water Department, City of Dover Water Department, and various municipal utilities. Common emergencies include freeze-thaw burst pipes, corroded cast iron drain lines, sewer backups, and water heater failures. Homeowners should insulate exposed pipes, test the main shutoff valve, and avoid pouring grease down drains.`,

  'mississippi': `Mississippi's plumbing systems face humid subtropical conditions, clay soils, and aging infrastructure. The Mississippi State Board of Plumbing licenses plumbers, and Jackson, Gulfport, and Biloxi enforce local plumbing codes. Many homes in the state were built between 1960 and 1990 with copper and PVC systems, though older neighborhoods still have galvanized steel and cast iron.

Expansive clay soils across the state shift with moisture changes, stressing slab foundations and underground plumbing. Hurricane season brings storm-driven sewer backups to Gulf Coast cities like Gulfport and Biloxi, where high water tables and coastal infrastructure are vulnerable. While winters are generally mild, occasional hard freezes can burst uninsulated outdoor pipes and hose bibs. Summer humidity accelerates corrosion and mold growth after leaks.

Water providers include the City of Jackson Water Department, City of Gulfport Water Department, and various municipal utilities. Common emergencies include aging infrastructure failures, storm-driven sewer backups, hurricane damage, and hard water scale accumulation. Homeowners should maintain sump pumps, clear drains before storm season, insulate outdoor fixtures, and flush water heaters annually.`,

  'north-dakota': `North Dakota's plumbing environment is shaped by some of the coldest winter conditions in the continental United States. The North Dakota State Plumbing Board licenses plumbers, and Fargo, Grand Forks, and Bismarck enforce local plumbing codes. Many homes in the state were built between 1960 and 1990 with copper supply lines and PEX in newer construction.

Winter is the dominant emergency driver. Temperatures in Fargo and Grand Forks regularly drop below zero for extended periods, with average winter temperatures of 5 to 10°F. Frozen pipes in basements, crawl spaces, and garages are the most common emergency. The rapid spring thaw can cause burst pipes as pressure returns to previously frozen lines. Hard water is significant, with levels of 165 to 180 ppm across the state, scaling water heaters and narrowing pipe openings.

Water providers include the City of Fargo Water Works, City of Grand Forks Water Works, and City of Bismarck Water Works. Common emergencies include frozen and burst pipes, hard water scale accumulation, water heater failures, and spring thaw pipe bursts. Homeowners should insulate all exposed pipes with heat tape, keep a backup heat source, and flush water heaters annually.`,

  'montana': `Montana's plumbing systems must handle high-altitude cold, hard water, and rocky soil conditions. The Montana State Plumbing Board licenses plumbers, and Billings, Missoula, Bozeman, and Helena enforce local plumbing codes. The state's semi-arid continental climate creates wide temperature swings that stress pipe joints and outdoor fixtures.

Winter temperatures regularly drop below zero across the state, with average winter temperatures of 18 to 24°F. Frozen pipes in uninsulated areas are the most common emergency, and the long freeze season extends from October through April. Hard water is widespread, with levels of 130 to 145 ppm, scaling water heaters and leaving deposits in fixtures. The rocky, alluvial soil makes excavation difficult and increases repair costs. Dry summers with large temperature swings stress pipe joints and cause leaks.

Water providers include the City of Billings Water Department, City of Missoula Water Department, and various municipal systems. Common emergencies include frozen pipes, hard water scale accumulation, water heater failures, and leaks from temperature swing stress. Homeowners should insulate all exposed pipes, drain hose bibs before winter, and flush water heaters annually.`,

  'wyoming': `Wyoming's plumbing environment is defined by high-altitude cold, extreme hard water, and rocky soil conditions. The state does not require statewide plumbing licensure, leaving regulation to local jurisdictions. Cheyenne, Casper, and Laramie enforce local plumbing codes and permit requirements. Many homes in the state were built between 1960 and 1990 with copper supply lines and PEX in newer construction.

Winter is the dominant emergency driver. Temperatures regularly drop below zero, with average winter temperatures of 18 to 22°F. Frozen pipes in uninsulated basements, crawl spaces, and garages are the most common emergency. Hard water is among the most severe in the nation, with Cheyenne recording 185 ppm, which scales water heaters rapidly and narrows pipe openings. The rocky, alluvial soil makes excavation difficult and expensive.

Water providers include the City of Cheyenne Board of Public Utilities, City of Casper Water Department, and City of Laramie Water Department. Common emergencies include frozen pipes, hard water scale blockages, water heater failures, and leaks from temperature swing stress. Homeowners should insulate all exposed pipes, install a water softener, and flush water heaters at least annually.`,

  'south-carolina': `South Carolina's plumbing systems face humid subtropical conditions, coastal exposure, and a mix of historic and modern housing. The South Carolina Department of Labor, Licensing and Regulation licenses plumbers through its Plumbing Division, and Charleston, Columbia, and Greenville enforce local plumbing codes. Many homes in Charleston's historic district were built before 1960 with cast iron and galvanized plumbing.

Coastal areas face salt air corrosion that attacks copper lines and metal fixtures, particularly in Charleston and North Charleston. Hurricane season brings storm-driven sewer backups and flooding to low-lying coastal areas with high water tables. The state's clay soils expand and contract with moisture, stressing slab foundations and underground plumbing. While winters are mild, occasional hard freezes can burst uninsulated outdoor pipes.

Water providers include Charleston Water System and various municipal utilities. Common emergencies include corrosion from salt air, storm-driven sewer backups, slab leaks from clay soil movement, and water heater failures. Homeowners should schedule annual corrosion inspections, maintain sump pumps, clear drains before hurricane season, and insulate outdoor fixtures.`,

  'maine': `Maine's plumbing environment is shaped by harsh winters, aging infrastructure, and rural water systems. The Maine Plumbers' Examining Board, under the Department of Professional and Financial Regulation, licenses plumbers, and Portland, Augusta, and Bangor enforce local plumbing codes. Many homes in the state's historic coastal towns were built before 1950 and still have galvanized steel, cast iron, and in some cases lead service lines.

Winter is the dominant emergency driver. Temperatures regularly drop below zero in interior areas, and the freeze season extends from October through April. Frozen pipes in uninsulated basements, crawl spaces, and exterior walls are the most common emergency. The spring thaw can cause burst pipes as pressure returns. Coastal towns face salt air corrosion that attacks metal pipes and fixtures. Many rural homes rely on well water and private septic systems, which have their own maintenance requirements.

Water providers include the Portland Water District, Augusta Water District, and numerous small municipal and private systems. Common emergencies include frozen and burst pipes, sump pump failures, corroded galvanized supply lines, and well pump failures. Homeowners should insulate all exposed pipes, test sump pumps before spring, and schedule annual well water testing.`,

  'new-hampshire': `New Hampshire's plumbing systems face severe winter freezes, aging New England housing stock, and a mix of urban and rural water systems. The New Hampshire Office of Professional Licensure and Certification licenses plumbers through its Board of Plumbers, and Manchester, Nashua, and Concord enforce local plumbing codes. Many homes in the state were built before 1970 and still have galvanized steel or cast iron plumbing.

Winter is the dominant emergency driver. Temperatures regularly drop below zero during January and February, and the freeze season extends from November through April. Frozen pipes in uninsulated basements and crawl spaces are the most common emergency. The spring thaw can cause burst pipes as pressure returns to previously frozen lines. Many rural homes rely on well water and private septic systems, which require regular maintenance and are vulnerable to freeze damage.

Water providers include the Manchester Water Works, Pennichuck Water Works, and numerous small municipal and private systems. Common emergencies include frozen and burst pipes, sump pump failures, well pump freeze damage, and water heater failures. Homeowners should insulate all exposed pipes, maintain a backup heat source, test sump pumps, and schedule annual well system inspections.`,

  'vermont': `Vermont's plumbing environment is defined by extreme cold, rural well-water systems, and aging housing stock. The Vermont Department of Public Safety, Division of Fire Safety, regulates plumbing through the state plumbing rules, and Burlington, Montpelier, and Rutland enforce local codes. Many homes in the state were built before 1960 and still have galvanized steel, cast iron, and copper plumbing that is vulnerable to freeze damage.

Winter is the dominant emergency driver. Temperatures regularly drop well below zero, and the freeze season extends from October through April. Frozen pipes in uninsulated basements, crawl spaces, and exterior walls are the most common emergency. The rapid spring thaw can cause burst pipes as pressure returns. Many rural homes rely on well water and private septic systems, which are vulnerable to freeze damage and require specialized maintenance. The state's mountainous terrain creates drainage challenges and foundation water issues.

Water providers include the Burlington Department of Public Works and numerous small municipal and private systems. Common emergencies include frozen and burst pipes, well pump failures, sump pump breakdowns, and septic system freeze-ups. Homeowners should insulate all exposed pipes, install heat tape on well lines, maintain a backup heat source, and test sump pumps before spring thaw.`,

  'west-virginia': `West Virginia's plumbing systems face mountain terrain, clay soils, harsh winters, and aging housing stock. The West Virginia Division of Labor regulates plumbing through its Plumbing Section, and Charleston, Huntington, and Morgantown enforce local plumbing codes. Many homes in the state were built before 1970 and still have galvanized steel or cast iron plumbing that is corroding from within.

Winter is the dominant emergency driver. Mountain terrain creates colder microclimates where temperatures drop below zero in higher elevations. Frozen pipes in uninsulated basements and crawl spaces are the most common emergency, and the spring thaw can cause burst pipes as pressure returns. The state's clay soils shift with moisture, stressing foundations and slab plumbing. Heavy spring rains can overwhelm older sewer systems and cause basement backups, particularly in Charleston and Huntington's older neighborhoods.

Water providers include West Virginia American Water and various municipal utilities. Common emergencies include frozen and burst pipes, sump pump failures, sewer backups, and leaks from aging galvanized and cast iron pipes. Homeowners should insulate all exposed pipes, test sump pumps before spring, and schedule camera inspections of older sewer laterals.`,
};
